### ISSUE TITLE
Can't access blog URL (www.sovereign.local) in vagrant test environment. SSL issue?

### ISSUE THREAD

**Issue by robfeldmann** [sovereign/sovereign#111]
Maybe this is expected, but I am unable to access the "blog" URL on the vagrant test machine. Browsing to `sovereign.local` or `www.sovereign.local` results in the following message (in Safari):

    Failed to open page: Safari can't open the page "https://www.sovereign.local" because Safari can't establish a secure connection to the server "www.sovereign.local"

This is what's in my `/var/log/apache2/error.log` file (after restarting apache):

    [Sun Dec 22 23:26:59 2013] [notice] caught SIGTERM, shutting down
    [Sun Dec 22 23:27:00 2013] [warn] RSA server certificate wildcard CommonName (CN) `*.sovereign.local' does NOT match server name!?
    [Sun Dec 22 23:27:00 2013] [warn] Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
    [Sun Dec 22 23:27:01 2013] [warn] RSA server certificate wildcard CommonName (CN) `*.sovereign.local' does NOT match server name!?
    [Sun Dec 22 23:27:01 2013] [warn] Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
    [Sun Dec 22 23:27:01 2013] [notice] Apache/2.2.22 (Debian) PHP/5.4.4-14+deb7u7 mod_ssl/2.2.22 OpenSSL/1.0.1e configured -- resuming normal operations

None of the other apache logs show any information. I'm sure I have my hosts file configured correctly and mail.sovereign.local loads up Roundcube perfectly. 

I would like to be able to test the blog URL to make sure it's loading which will help me work on an Apache virtual host issue I'm trying to solve. Thanks!

**Comment by lukecyca** [comment]
Not going to get to this, unfortunately. This is such a minor issue that I am just going to close it.

**Comment by neuhaus** [comment]
I hope we can get rid of those expensive wildcard certificates soon and replace them with a bunch of free "lets-encrypt"-certs.
