### ISSUE TITLE
Make encfs optional

### ISSUE THREAD

**Issue by Anonymouslemming** [sovereign/sovereign#120]
How hard would it be to make encfs optional ? 

I run this on my own host on my own network, and I want it mounted at boot time. Doing this means storing the password somewhere on the host. If my host is siezed, they will be able to recover the password anyway, so I don't see the value to encfs in this operating model. 

Looking at the playbooks and the resulting installation, many of the applications expect their content to be available at /decrypted. Would it be possible to include the data directory as a variable in the user.yml vars file? 

Removing encfs would also make these playbooks work with Ubuntu 13.10. This currently fails as there is no fuse-utils package in the default repos.

**Comment by shaneonabike** [comment]
As well you will need to remove the fuse group from the user at roles/common/tasks/users.yml since this will fail the install also!

**Comment by neuhaus** [comment]
Btw, there is also the possibility to run ansible with the option `--skip-tags "encfs"`

**Comment by neuhaus** [comment]
Thanks @shaneonabike for your observation, I removed the group "fuse" from users.yml and moved it to encfs.yml instead, making it optional.
