### ISSUE TITLE
Move all private information to its own config file

### ISSUE THREAD

**Issue by do3cc** [sovereign/sovereign#164]
This serves more as a reminder that I am going to work on this as time permits.

In some of the deployment tools one can store private data encrypted with key that is not shared. If I check in my encrypted data into a public repo, everybody already has my data, just encrypted. If my key some time gets out in the wild, all private data is exposed.
Instead I'd rather have a specifc config file that is in gitignore and maybe a python script to to fill this config file initially. The configuration does not need to contain domains or ports, only passwords, and if configurable, usernames. People would be responsible on their own to back up this file.

**Comment by mikeashley** [comment]
I believe this issue has been addressed.  Secrets are moved to a separate folder, and the folder is in `.gitignore`.  Ansible will populate these secrets with randomly-generated passwords if they don't exist.  Users are responsible for backing up their secrets.
