### ISSUE TITLE
Roundcube database error after plain vanilla install

### ISSUE THREAD

**Issue by yuvadm** [sovereign/sovereign#184]
Roundcube doesn't work and shows:

> DATABASE ERROR: CONNECTION FAILED!
> Unable to connect to the database!
> Please contact your server-administrator.

Logs show:

``` bash
$ tail /var/log/roundcube/errors
[09-Mar-2014 22:43:42 +0200]: DB Error: no RDBMS driver specified in /usr/share/roundcube/program/include/rcube_mdb2.php on line 104 (GET /)
```

**Comment by shaneonabike** [comment]
Thanks very much @wgailey ! That really helped it's now working!
