### ISSUE TITLE
Upgrading/Migrating from MySQL to PostgreSQL?

### ISSUE THREAD

**Issue by jgillman** [sovereign/sovereign#218]
I originally created my server when Sovereign was using MySQL. Earlier today I needed to update my SSL cert (due to Heartbleed), so I grabbed the latest Sovereign and went to town. Now Roundcube is reporting "DATABASE ERROR: CONNECTION FAILED!".

What steps can I take to resolve this? I'd love not to loose all of my past emails is possible, though it wouldn't be the end of the world.

**Comment by dr-nate** [comment]
If anyone else ends up with this error https://github.com/sovereign/sovereign/issues/218#issuecomment-40158945, in my case it was an issue with the password. In my `vars/user.yml` file, I mistakenly put the password *hash*, and not the password, in the `mail_db_password` line (oops).

Conceivably, this could also happen if for some other reason the password you're entering in the `mail_db_password` line doesn't match up exactly with that already in the postgresql database for the roundcube user.
