### ISSUE TITLE
Configure SSH to use OATH with public key auth

### ISSUE THREAD

**Issue by neuhaus** [sovereign/sovereign#246]
OpenSSH 6.3 or later supports combining OATH auth with public key auth. This would be great to have in sovereign!
It is described at https://www.insecure.ws/linux/openssh_oath.html
With previous versions, google authenticator is only used for password authentication.

Unfortunately, Debian wheezy ships with OpenSSH 6.0 but Ubuntu trusty comes with OpenSSH 6.6.

**Comment by al3x** [comment]
My preference is to keep Sovereign aligned with Debian stable, primarily.

**Comment by neuhaus** [comment]
OK, let's put this on hold until debian stable ships with OpenSSH 6.3+ (or until someone else makes a nice PR ;-) )

**Comment by Yannik** [comment]
Debian stable now ships OpenSSH 6.7.

**Comment by neuhaus** [comment]
So, the underlying software is ready for this, all we need is someone to provide a pull request. Until then I'm closing this issue.
