### ISSUE TITLE
Use luasec-prosody instead of luasec

### ISSUE THREAD

**Issue by antagonismorg** [sovereign/sovereign#285]
See https://prosody.im/doc/depends/luasec/prosody

This would allow the following:

    Certificate verification (needed to support certificate authentication for s2s connections)
    Perfect Forward Secrecy ciphers (DHE and ECDHE)
    APIs that allow channel binding (e.g. the SCRAM-SHA-1-PLUS SASL mechanism)
    Controls over CRL checking

**Comment by neuhaus** [comment]
Jessie comes with lua-sec 0.5

**Comment by neuhaus** [comment]
Since 570bebac704f5515dcc88c82746de160400f397d we install the **lua-sec** 0.5 package on Ubuntu Trusty and Debian Jessie where it is available.
And since commit edf65c530a07ebcf15b457457a9139bfad13406f we use **lua-sec-prosody** on Ubuntu Precise and Debian Wheezy. 
Fixed.
