### ISSUE TITLE
Roundcube: Connection to storage server failed.

### ISSUE THREAD

**Issue by pedrovanzella** [sovereign/sovereign#297]
Whenever I try to connect to Roundcube, all I get is `Connection to storage server failed.`.

I can't connect to IMAP or SMTP either.

My `mail.err` reads:

```
root@mail:/home/deploy# tail /var/log/mail.err
Aug 29 19:28:30 mail dovecot: imap-login: Error: SSL: Stacked error: error:0608308E:digital envelope routines:EVP_PKEY_get1_EC_KEY:expecting a ec key
Aug 29 19:28:30 mail dovecot: imap-login: Fatal: Can't load ssl_cert: error:0906D066:PEM routines:PEM_read_bio:bad end line
Aug 29 19:36:10 mail dovecot: imap-login: Error: SSL: Stacked error: error:0608308E:digital envelope routines:EVP_PKEY_get1_EC_KEY:expecting a ec key
```

My `mail.log` reads:

root@mail:/home/deploy# tail /var/log/mail.log
    Aug 29 20:12:53 mail postfix/smtpd[6193]: disconnect from localhost[127.0.0.1]
    Aug 29 20:12:53 mail dovecot: imap-login: Error: SSL: Stacked error: error:0608308E:digital envelope routines:EVP_PKEY_get1_EC_KEY:expecting a ec key
    Aug 29 20:12:53 mail dovecot: imap-login: Fatal: Can't load ssl_cert: error:0906D066:PEM routines:PEM_read_bio:bad end line
    Aug 29 20:14:53 mail postfix/postscreen[6294]: CONNECT from [127.0.0.1]:35425 to [127.0.0.1]:25
    Aug 29 20:14:53 mail postfix/postscreen[6294]: WHITELISTED [127.0.0.1]:35425
    Aug 29 20:14:53 mail postfix/smtpd[6295]: warning: cannot get RSA certificate from file /etc/ssl/certs/wildcard_combined.pem: disabling TLS support
    Aug 29 20:14:53 mail postfix/smtpd[6295]: warning: TLS library problem: error:0906D066:PEM routines:PEM_read_bio:bad end line:pem_lib.c:802:
    Aug 29 20:14:53 mail postfix/smtpd[6295]: warning: TLS library problem: error:140DC009:SSL routines:SSL_CTX_use_certificate_chain_file:PEM lib:ssl_rsa.c:730:
    Aug 29 20:14:53 mail postfix/smtpd[6295]: connect from localhost[127.0.0.1]
    Aug 29 20:14:53 mail postfix/smtpd[6295]: disconnect from localhost[127.0.0.1]

Also, it seems to cause fail2ban to stop working:

```
root@mail:/home/deploy# fail2ban-client status
ERROR  Unable to contact server. Is it running?
root@mail:/home/deploy# service fail2ban start
 * Starting authentication failure monitor fail2ban 
 ERROR  No file(s) found for glob /var/log/maillog
ERROR  Failed during configuration: Have not found any log file for dovecot-pop3imap jail
                     [fail]
```

**Comment by shaneonabike** [comment]
I tried to rerun as suggested and that didn't work and now I seem to be experiencing the same problem as mentioned above. Any help would be awesome!

<code>

[12-Feb-2015 05:14:49 +0000]: IMAP Error: Login failed for shane@beesonabike.com from 108.161.114.223. Could not connect to ssl://127.0.0.1:993: Unknown reason (fsockopen() function disabled?) in /usr/share/roundcube/program/lib/Roundcube/rcube_imap.php on line 184 (POST /?_task=login&_action=login)

</code>

**Comment by shaneonabike** [comment]
Could this be related? https://bbs.archlinux.org/viewtopic.php?id=187063

**Comment by talaweb** [comment]
Login to server or VPS and run: service dovecot restart

**Comment by shaneonabike** [comment]
Unfortunately, that didn't do anything and it seems that dovecot cannot startup the imap-login?

**Comment by zardan87** [comment]
Hi,

I just encounterd the "Connection to storage server failed" with mailinabox and after logging in to the box and checking the /var/log/roundcube/errors I noticed this error:

19-Jul-2018 11:36:20 Europe/Berlin] PHP Warning:  stream_socket_client(): unable to connect to ssl://localhost:993 (Connection timed out) in /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_imap_generic.php on line 959

So I tried telnet localhost 993 which also timed out, but i noticed it trying to connect to ::1 instead of 127.0.0.1 so I edited /etc/gai.conf and removed the # in front of this line:

#precedence  ::/0          40

And then it worked like it should again. I hope this helps someone!

**Comment by codecowboy** [comment]
@nikade87 what does gai.conf configure?

**Comment by nikade87** [comment]
> @nikade87 what does gai.conf configure? Can you explain what this fixes?

This configuration will tell the system to prefer ipv4 over ipv6. Since most of the services in mailinabox will listen to 127.0.0.1 and not ::1 it would resolve some connectivity issues
