### ISSUE TITLE
UFW script locks you out of remote host access

### ISSUE THREAD

**Issue by ipartola** [sovereign/sovereign#303]
Currently, roles/common/tasks/ufw.yml task Deny everything and enable UFW seems to enable the firewall too early on. This means that all connections will be dropped before the exception for ssh is made. This is very problematic when running ansible over SSH on a remote host. Ideally, the firewall should be enabled as the last step in this task.

**Comment by shaneonabike** [comment]
This hasnt been resolved for me and I was completely locked out of my server after the apache was attempted to be restarted
