### ISSUE TITLE
Rebooting the machine unmounts encripted file store (encfs.yml)

### ISSUE THREAD

**Issue by Debugreality** [sovereign/sovereign#317]
I noticed this after rebooting my virtual box with Debian wheezy.

Adding the following to the end of encfs.yml works but I'm not sure if this is the best solution as it adds your encryption password in plain text. Also rc.local is not the recommended way to add on boot scripts.

# Need to set up to mount on boot
- name: remount encfs on boot
  lineinfile: dest=/etc/rc.local regexp='encfs /encrypted /decrypted --public --stdinpass' insertbefore='^exit 0' line='printf "{{ encfs_password }}" | encfs /encrypted /decrypted --public --stdinpass'

**Comment by neuhaus** [comment]
Having to enter the passphrase for encfs after the reboot is exactly the whole point of encrypting a filesystem in the first place.

If someone confiscates or steals your server you want them unable to access your files.
