### ISSUE TITLE
RC4 considered broken

### ISSUE THREAD

**Issue by neuhaus** [sovereign/sovereign#341]
RC4 has had some bad press lately, I think we should disable it (in Apache etc.). This breaks only IE6 on Windows XP afaik.
If there are no objections I'll make a PR.

**Comment by stephenjamieson** [comment]
it could break on some old androids, but in my opinion that's ok.

**Comment by neuhaus** [comment]
Android 2.3.7 doesn't even support [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) which means we are already incompatible.

I have a site configured without RC4 and according to https://www.ssllabs.com/ssltest/ the only `Protocol or cipher suite mismatch` is with IE6+XP.

**Comment by al3x** [comment]
@neuhaus Please do submit a PR :sunglasses:

**Comment by neuhaus** [comment]
Not sure what the best `SSLCipherSuite` is (there doesn't seem to be a big difference - i have these three in use they all do the trick:

    SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AES:RSA+3DES:!ADH:!AECDH:!MD5:!DSS
    SSLCipherSuite "EECDH+AESGCM EDH+AESGCM EECDH -RC4 EDH -SEED !aNULL !eNULL !LOW !3DES !AES128 !MD5 !EXP !PSK !SRP !DSS !RC4 HIGH"
    SSLCipherSuite "EECDH+AESGCM EDH+AESGCM EECDH -RC4 EDH -SEED !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS !RC4 HIGH"

**Comment by neuhaus** [comment]
Mozilla has some recommendations and a config builder at https://wiki.mozilla.org/Security/Server_Side_TLS

Here is the recommended SSLCipherSuite for the "modern" setting:
`SSLCipherSuite ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK`

I will make a pull request with that one.
