### ISSUE TITLE
Using openDMARC

### ISSUE THREAD

**Issue by shaneonabike** [sovereign/sovereign#369]
After I first ran sovereign things were working swingly, but all my emails were ending up in peoples spam folders (on a new IP and server) which seemed weird.

I read around and finally came across DMARC (https://stackoverflow.com/questions/11683580/spam-is-being-sent-using-my-domain-what-can-i-do) and an opensource version to implement that (http://blog.hamzahkhan.com/2014/02/08/securing-postfix-mail-server-greylisting-spf-dkim-dmarc-tls/).

I am going to give that a shot on my server and report back. I thought it could be useful for others since having blocked email right out of the box isn't so great :/

**Comment by shaneonabike** [comment]
Sorry actually this tutorially is a bit better http://www.skelleton.net/2015/03/21/how-to-eliminate-spam-and-protect-your-name-with-dmarc/#dmarc_postfix

There's also a nice little wizard here that helps you generate a dmarc http://kitterman.com/dmarc/assistant.html

**Comment by al3x** [comment]
I haven't had major issues with outgoing email from my Sovereign server being marked as spam, but I agree that we should support DMARC. I'll try to get it going on my box as well. Pull requests are always appreciated :)

**Comment by shaneonabike** [comment]
I totally understand Alex...!
    
    I'm still working on trying to build the mysql version switch but
    haven't done that just yet. Once that's done you could pull that and
    I could add the other.
    
    I am also not sure why all my emails are going to spam especially on
    a new server, but apparently DMARC should help (crossing my fingers)
    
    On 15-05-11 11:02 AM, Alex Payne wrote:
    
    
      I haven't had major issues with outgoing email from my
        Sovereign server being marked as spam, but I agree that we
        should support DMARC. I'll try to get it going on my box as
        well. Pull requests are always appreciated :)
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
      
        Shane Bill
        Web Development & Consultant
        
          
            
              E-mail
              shanebill@gmail.com
                
            
            
              Phone
              438-934-2624
            
            
              More information
              https://develop.beesonabike.com

**Comment by lukecyca** [comment]
Great idea. I'm going to read up on this too.

**Comment by al3x** [comment]
I got it implemented on my server as per that skelleton.net blog post earlier today. So far so good. I want to live with it for a couple days before I submit a PR, see if there are any issues.

One thing that post details is how you'd make anti-spam software aware of DMARC. It provides examples for SpamAssassin, but we use dspam. It remains to be seen whether that additional step is necessary.

**Comment by shaneonabike** [comment]
Yeah I noticed that too... I finally got a post back from Google recognizing my DMARC which is cool. Here's the referencing documentation in the XML I got.. https://support.google.com/a/answer/2466563?hl=en&ref_topic=2759254

In that they indicate that they don't accept forensic posts and I am cautious to think that Yahoo or others do either.
