### ISSUE TITLE
Update for Debian Jessie

### ISSUE THREAD

**Issue by al3x** [sovereign/sovereign#370]
Debian 8 "Jessie" is now the stable release of Debian, the primary supported Linux distribution for Sovereign. We should get the playbooks and Vagrant configuration up to date for it.

**Comment by miloshadzic** [comment]
Interested in this as well. What needs to be changed? I'm guessing systemd is the biggest change?

**Comment by neuhaus** [comment]
I'm also willing to help here.

**Comment by Yannik** [comment]
For dovecot, you guys will want to diff your existing `/etc/dovecot` against `/usr/share/dovecot`. I recommend merging file-by-file using vimdiff. There are quite a few changes.

**Comment by al3x** [comment]
This work will be happening in https://github.com/al3x/sovereign/tree/jessie if anyone wants to pitch in.

**Comment by keybits** [comment]
Happy to help with this. Any suggestions on what needs working on? Or just try it out and send PRs?

**Comment by al3x** [comment]
My approach was going to be to just keep running the playbooks against my local Vagrant instance until everything works :) Nothing particularly focused.

**Comment by al3x** [comment]
Just wanted to let folks know that if they want Jessie support, don't wait on me. I have little to no time to work on Sovereign for the foreseeable future. Hopefully the community can step up here.

**Comment by mikeashley** [comment]
Looks like Issue #440 is where this is getting discussed.  Closing this issue to clean up.
