### ISSUE TITLE
Fix Postfix submission port configuration

### ISSUE THREAD

**Issue by Yannik** [sovereign/sovereign#374]
I noticed that the submission protocol is disabled in [master.cf](https://github.com/al3x/sovereign/blob/master/roles/mailserver/files/etc_postfix_master.cf).

According to [RFC6409](https://tools.ietf.org/html/rfc6409), the submission protocol / port 587 is 
  - the port which should be used for mails from a MUA (mail user agent)
  - must require authentication
  - for client->server communication.

Port 25/465 are for message relay, which is server->server communication. Port 465 uses SSL/TLS before the smtp communication starts, while 25 shall promote starttls via smtp protocol which may be used to upgrade the connection to use SSL/TLS. Port 465/ssmtp has been deprecated in 1998(!).

Even though this settings seems to exist since the first commit to the project, there has been a bit of discussion about this: https://github.com/al3x/sovereign/pull/318
This discussion is ended by stating that STARTTLS is less secure then using ssmtp, because ISPs previously tampered with the STARTTLS flag. In this case, this is untrue the submission protocol/port 587 should definitely be used. By using `smtpd_tls_auth_only = yes` in [master.cf](https://github.com/al3x/sovereign/blob/master/roles/mailserver/templates/etc_postfix_main.cf.j2#L46), it is already ensured that clients can only authenticate when using tls, mitigating any tampering from ISPs.

I happened to stumble upon this when looking through your project, but don't actually use it, and therefore don't have a complete overview of your config. Because of this, even though I'm a professional mailserver admin, I ask you to create a PR for this yourself keeping your complete config in mind.

**Comment by Yannik** [comment]
Your [autoconfig](https://github.com/al3x/sovereign/blob/master/roles/mailserver/templates/var_www_autoconfig_mail_config-v1.1.j2) must be adjusted accordingly.

**Comment by ariddell** [comment]
@Yannik Thanks for taking the time to leave these useful reports.

**Comment by al3x** [comment]
Yes indeed! Lots to work on in the coming days.

**Comment by neuhaus** [comment]
@Yannik Thank you for opening this issue.
If there is an active man-in-the-middle attack (such as stripping STARTTLS), the clients must be configured to enforce STARTTLS, otherwise the attacker can talk plain text to the client and use STARTTLS while talking to the server.

That said, I think adding the submission port is The Right Thing.

**Comment by Yannik** [comment]
@neuhaus Yeah, that's true. We need something like HSTS for smtp :)

**Comment by ariddell** [comment]
@Yannik Until we have HSTS for smtp, what are the practical consequences of simply disabling/firewalling submissions on port 25 (but still allowing them on 587). I realize this is a bad idea -- but is it a horrible idea?

**Comment by neuhaus** [comment]
Port 25 needs to remain open for mail arriving from other MTAs (not MUAs).

**Comment by ariddell** [comment]
Oh, I thought there was a secure port for MTAs as well. In that case, can you block any submissions from MTAs which don't use STARTTLS on port 25? Or is this a horrible idea?

**Comment by neuhaus** [comment]
I think you can configure Postfix to reject unencrypted mails received via port 25, however I think that will result in a lot of undelivered email, so we should not make that the default. Let's hope that soon this will be more feasible.

**Comment by ariddell** [comment]
Personally, I wouldn't mind receiving fewer emails. What MTAs are not encrypting these days?

**Comment by neuhaus** [comment]
I checked a few emails and it appears I receive more then 25% of email that reaches my server without TLS. YMMV. Perhaps you only get mail from gmail? In that case, there is no privacy anyway 😢

**Comment by ariddell** [comment]
25% is far more than I would have expected. Thanks!

**Comment by ariddell** [comment]
It looks like I'm not crazy. If/when this gets finalized, it would be cool if sovereign could support it.

IETF Draft: SMTP Require TLS Option

https://datatracker.ietf.org/doc/draft-fenton-smtp-require-tls/

**Comment by Yannik** [comment]
I only read a few passages of the proposal: It seems a) unrelated to this issue b) not very useful to me. 
Some providers already allow their users to select whether an email should only be delivered if it can be done in an encrypted fashion. (see for example https://mailbox.org/en/ensuring-emails-are-sent-securely/). 
It also a) requires sysadmins of the receiving servers to change their system b) users to adapt (apart from software updates needed for MTAs and MUAs). It effectively secures MTA->MTA traffic.
DANE is superior for this IMO and needs only the sysadmins of the receiving system to implement changes. (Even though it definitely is harder to achieve than to just update your MTA to a version which supports REQUIRETLS)

So, back to this issue: It largely depends whether an MUA is configured to figure out whether the remote smtp server supports TLS automatically at each connection, or whether it is done once at the setup of the account (may be assisted to choose the right values using autoconfiguration). Most often, it's probably the latter option that is used. If an downgrade attack occurs after this initial account setup, the user is secure as the connection will fail because it's client is configured to use STARTTLS.

So, there is not really an issue with enabling this (and shutting down SMTPS/ port 465).

Btw, this is a utility you can test stripping STARTTLS with: https://github.com/tintinweb/striptls
In this case (as this utility supports so many other ways to manipulate STARTTLS connections, you probably want to use `striptls --listen 0.0.0.0:588 --remote localhost:25 --vectors=SMTP.StripFromCapabilities`. Now you can just set your client to connect to port 588 and you will see whether the stripping attack works or not.

Works like a charm - fortunately, only

**Comment by ariddell** [comment]
You're right. I just need to set ``smtpd_tls_security_level`` to ``encrypt``, right?

**Comment by Yannik** [comment]
You can do that for the submission port, but don't do it for port 25.

**Comment by Yannik** [comment]
This issue was about enabling submission (port 587), see https://github.com/sovereign/sovereign/blob/master/roles/mailserver/files/etc_postfix_master.cf#L16.

**Comment by mikeashley** [comment]
I am considering fixing this and submitting a PR.  I think it will break client configurations, and we'll all have to fix up our clients.  Are we ok with that?  It's a little painful for me, since I have a few family members I will have to help through the change, but I consider it worth it to make this right.

**Comment by ariddell** [comment]
This should definitely be fixed.

**Comment by neuhaus** [comment]
Having both ports open for a while should not be a problem, right?

--

**Comment by mikeashley** [comment]
In principal, no, it's not a problem.  In PR #560 I closed 465 since leaving it open defers the transition users would need to make when 465 is eventually closed.  I think it is easier to communicate the change at the same time we switch to Jessie.

**Comment by mikeashley** [comment]
I closed 465 with commit 16dc7d now that we're closed to the Jessie switch.  This is documented on the migration page on the wiki in the handful of backwards-incompatible changes we have.  I believe this last patch resolves this issue.
