### ISSUE TITLE
Use dovecot lmtp instead of lda

### ISSUE THREAD

**Issue by Yannik** [sovereign/sovereign#375]
Quote from http://wiki2.dovecot.org/LDA:
`The Dovecot LDA is a local delivery agent, which takes mail from an MTA and delivers it to a user's mailbox, while keeping Dovecot index files up to date. Nowadays you should probably use the LMTP server instead, because it's somewhat easier to configure (especially related to permissions) and gives better performance.`

This basically sums up why I'd recommend you to use dovecot lmtp instead of lda. lda is a short running process which is started everytime a mail is delivered while dovecot lmtp is long running and doesn't have the associated overhead of starting a process each time.

**Comment by Yannik** [comment]
You will need to set `virtual_transport = lmtp:unix:private/dovecot-lmtp` in `master.cf` and enable dovecot lmtp if it isn't already enabled (didn't check this for your setup).

**Comment by neuhaus** [comment]
Can you do a pull request please?

**Comment by Yannik** [comment]
Sorry, I got no ressources/time for that atm.
