### ISSUE TITLE
Moving to GitHub org, adding other maintainers

### ISSUE THREAD

**Issue by al3x** [sovereign/sovereign#380]
I'm concerned about becoming a bottleneck for future work on Sovereign. I'd like to move the project to the https://github.com/sovereign organization that @lukecyca grabbed a while ago, and in the process add some other maintainers who can push changes to `master` without waiting for my approval.

Right now, @lukecyca is the only other maintainer, and he's also quite busy. I'd like to invite @neuhaus, @ariddell, @synchrone, @jplock, @lvillani and whoever else would like to put their hands up to join as maintainers.

Sound good? Any objections?

**Comment by lukecyca** [comment]
Great idea

**Comment by jplock** [comment]
Sounds great to me

**Comment by neuhaus** [comment]
Thumbs up from me!

-Sven

**Comment by neuhaus** [comment]
Let's use this opportunity to set up some guidelines for everything that is added to the master branch. 
My suggestion: Commits should be tested on Debian stable and Ubuntu LTS.

-Sven

**Comment by case** [comment]
:+1:

**Comment by ariddell** [comment]
Sure! re: @neuhaus, perhaps it might be a good time to write a ``CONTRIBUTING.md`` (which github will show users submitting PRs)? For more elaborate examples, there's zeromq's "Development Process" http://rfc.zeromq.org/spec:22 and OpenStack's Hacking guidelines: http://docs.openstack.org/developer/hacking/

**Comment by al3x** [comment]
I've completed the migration to the new GitHub organization. Thanks again for grabbing that, @lukecyca.

I've sent invitations to the contributors who've posted in this thread. I'm going to leave the issue open for several more days to let others put their hands up if they'd also like to be considered for the commit bit.

@ariddell: we now have a `CONTRIBUTING.md` document. I don't think it'll end up being as exhaustive as OpenStack's, but right now it's just a stub.

**Comment by lukecyca** [comment]
Great work, @al3x! I like that our org's identicon looks a bit like a castle turret. I guess that's as good a pictogram for "Sovereign" as any.

![](https://avatars2.githubusercontent.com/u/6289855)

**Comment by lvillani** [comment]
@al3x Thanks for the invite! Since I've been inactive for a while, though, I prefer to submit contributions "the usual way" by forcing my stuff to go through review via pull requests so as to avoid making more harm than good :wink:

**Comment by neuhaus** [comment]
I think there are some points we need to discuss, should we do it in issues like this one or perhaps set up a mailing list?

Here are some areas of discussion for this project:

* future project direction
* software choices such as Apache vs. Nginx
* configuration choices (e.g. more secure vs. better interoperability)

**Comment by al3x** [comment]
I'd prefer to see these be discussed in issues . We can add a "discussion" label in the issues settings for the project.

**Comment by neuhaus** [comment]
Sounds good, please add the "discussion" label.

**Comment by al3x** [comment]
All three labels added.

Nobody else has put their hands up for commit privileges, so I'm closing this.

**Comment by neuhaus** [comment]
If @mikeashley is interested in commit privilege, I think he deserves it by now :-)

**Comment by mikeashley** [comment]
I'm interested.  Thank you for the consideration.

**Comment by neuhaus** [comment]
@ariddell thankfully opened issue #501 for this
