### ISSUE TITLE
deb mirror not working ... 

### ISSUE THREAD

**Issue by TheFu** [sovereign/sovereign#382]
TASK [common : Update apt cache] ************************************************
fatal: [172.22.22.9]: FAILED! => {"msg": "BECOME-SUCCESS-kzrnofpndwfopugwlqyrjlwohrmsvhaz\r\nTraceback (most recent call last):\r\n  File \"/home/deploy/.ansible/tmp/ansible-tmp-1433607390.18-22285734784911/apt\", line 2085, in <module>\r\n    main()\r\n  File \"/home/deploy/.ansible/tmp/ansible-tmp-1433607390.18-22285734784911/apt\", line 423, in main\r\n    cache.update()\r\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 440, in update\r\n    raise FetchFailedException 

this goes on and on.
We use apt-cacher-ng.  If it is configured, the deb-mirror method doesn't work. Had to restore from a system backup to get it working again.

Ansible 2.0.0 - dev version (had v1.5, updated)
Ubuntu 14.04 server on both sides.
ssh connection is working.

Commented out the first stanza in roles/common/tasks/main.yml to get passed this issue. My ansible-fu isn't strong enough to check whether a proxy is configured for ansible or not. The setup is not standardized across debian/ubuntu servers.  This is mine:
$ more /etc/apt/apt.conf.d/02proxy 
Acquire::http { Proxy "http://istar:3142"; };

**Comment by neuhaus** [comment]
So do you think apt-cacher-ng is the culprit?

**Comment by TheFu** [comment]
Yes. It is a known issue in apt-cacher-ng.  
Downgraded to Ansible 1.9.x and attempted an install. It got further (but was stuck somewhere else).

**Comment by neuhaus** [comment]
OK. Please get it fixed in apt-cacher-ng then. Thanks.
