### ISSUE TITLE
Task "Download Google authenticator pam module" fails

### ISSUE THREAD

**Issue by felixkiss** [sovereign/sovereign#384]
Target System: Debian 7 x64
Ansible Version: 1.9.0.1

Output:
```
TASK: [common | Download Google authenticator pam module] *********************
failed: [SERVER_IP] => {"dest": "/root/libpam-google-authenticator-1.0-source.tar.bz2", "failed": true, "response": "HTTP Error 403: Forbidden", "state": "absent", "status_code": 403, "url": "https://google-authenticator.googlecode.com/files/libpam-google-authenticator-1.0-source.tar.bz2"}
msg: Request failed
```

Link is valid. Any suggestions for a workaround?

**Comment by felixkiss** [comment]
Workaround for now: Download it manually, place it in `/root` and comment out `Download Google authenticator pam module` task

**Comment by neuhaus** [comment]
I just tested it here, works for me

**Comment by felixkiss** [comment]
I changed my VPS to Ubuntu 14.04 and it worked fine as well. 

I don't know what caused the 403 but I'm closing the issue as not reproducible.
