### ISSUE TITLE
vagrant box choice

### ISSUE THREAD

**Issue by neuhaus** [sovereign/sovereign#385]
Hello @al3x 

just wondering - why do you use the dhoppe boxes for the jessie branch instead of the box-cutter ones?

**Comment by al3x** [comment]
Because box-cutter didn't release boxes for Jessie final [onto Atlas](https://atlas.hashicorp.com/boxes/search?utf8=✓&sort=updated&q=box-cutter) until several days ago. We can move back to those if you like.

**Comment by neuhaus** [comment]
Sure, there's a box-cutter image for jessie 8.1 now.
