### ISSUE TITLE
Install collectd 5.4+ from packages (on Trusty and Jessie)

### ISSUE THREAD

**Issue by neuhaus** [sovereign/sovereign#387]
Currently, sovereign builds collectd 5.4.1 from source.

On Ubuntu Trusty and Debian Jessie we can use the official packages instead. They ship with collectd 5.4.0 and 5.4.1, respectively.

**Comment by neuhaus** [comment]
Also, I noticed that since August 2014 the collectd-librato plugin has been deprecated.
See https://github.com/librato/collectd-librato/blob/master/README.md
It should be replaced using the Collectd Write HTTP plugin, apparently.
I don't know anything about collectd and/or librato so preferably someone else should make this change.

**Comment by al3x** [comment]
This is done in the `jessie` branch.
