### ISSUE TITLE
Update wallabag version

### ISSUE THREAD

**Issue by neuhaus** [sovereign/sovereign#388]
Apparently there is a security fix in version 1.7.2, sovereign still uses 1.7.1
The current version is 1.9.0

Someone needs to check if config changes are necessary...

**Comment by simontretter** [comment]
I just tried wallabag_version: 1.7.2. No obvious problems so far.

**Comment by neuhaus** [comment]
Thanks. Could you also try 1.9.0?

**Comment by simontretter** [comment]
Tried that as well, but changing the version number in vars seems to to break the playbook. It does not pull from github. I'll see why.

**Comment by simontretter** [comment]
Same for 1.9.0, no obvious things going wrong. Note though that the actual git version number is 1.9 (not 1.9.0).
