### ISSUE TITLE
postgrey fails to start without proper ipv6 configuration

### ISSUE THREAD

**Issue by simontretter** [sovereign/sovereign#390]
After a server restart, all mails sent to my sovereign installation started to bounce back. This seemed to be due to postgrey not running. After changing POSTGREY_OPTS in /etc/default/postgrey from "--inet=10023" to "--inet=127.0.0.1:10023", it could be started again.

I am sure most of you have no reason to disable ipv6 and prefer to have postgrey and postfix interacting over ipv6 instead of ipv4. In my case, the default behaviour of using ipv6 caused troubles though.

**Comment by al3x** [comment]
Noted, thanks. Hopefully if this is an issue for anyone they'll find this issue and your fix.

**Comment by ITNerdbox** [comment]
Thanks @simontretter - fixed my issue after searching for a proper solution for a while.

**Comment by ITNerdbox** [comment]
I've discovered another issue where postgrey could not be started with _/etc/init.d/postgrey_ or _service postgrey start_. The solution was to start it manually (I know, not the best option) 

> /usr/sbin/postgrey --daemonize --inet=127.0.0.1:10023 --group=postgrey --user=postgrey --greylist-text=Greylisted for %%s seconds --delay=60
