### ISSUE TITLE
Replace dspam with Rspamd

### ISSUE THREAD

**Issue by plotters** [sovereign/sovereign#394]
dspam is removed as of Debian 8: https://tracker.debian.org/pkg/dspam
Is there a good replacement?

**Comment by ariddell** [comment]
That's a shame. Apparently it's not maintained upstream: https://tracker.debian.org/news/558416

**Comment by al3x** [comment]
That's going to be a minor PITA to swap out. Guess it's SpamAssassin for us, or maybe [Anti-Spam SMPT Proxy](https://en.wikipedia.org/wiki/Anti-Spam_SMTP_Proxy)?

**Comment by neuhaus** [comment]
I found no packages for ASSP on Debian, let's pick something that has packages available and in the default distribution. Spamassassin is probably the most straightforward choice.

**Comment by florianbeer** [comment]
This is really bad! Dspam was working so well for me, now I'm much more on the fence about upgrading to Jessie :(

**Comment by plotters** [comment]
Any thoughts on this one:  https://www.rspamd.com/ ?

**Comment by al3x** [comment]
Looks like a really strong choice. Actively maintained, good feature list, Google Summer of Code support.

**Comment by al3x** [comment]
Just pushed [the beginnings of an Rspamd](https://github.com/sovereign/sovereign/commit/ecaa4c23308adbdb5d76937296090ca7a6cc5944) implementation in our `jessie` branch.

Still need the task to configure [Rmilter](https://rspamd.com/rmilter/) to be aware of [Rspamd](https://www.rspamd.com/doc/integration.html). Postfix configuration will pick up Rmilter and should "just work" from there.

**Comment by carljm** [comment]
I'm working on finishing this out, and ran into a question. Apparently rmilter also has DKIM signing and validation support (using OpenDKIM under the hood). Should I disable that in the rmilter config, and use rmilter only for rspamd, and continue using OpenDKIM's own milter? Or should we just let rmilter handle both, and reduce from three down to two milters? Any opinions?

**Comment by mikeashley** [comment]
We can close this since rspamd is integrated.  I created issue #529 to consider removing OpenDKIM's milter.
