### ISSUE TITLE
Include owncloud signing keys directly in the role

### ISSUE THREAD

**Issue by ypid** [sovereign/sovereign#398]
See https://github.com/jchaney/owncloud/pull/12

**Comment by mikeashley** [comment]
Currently they are downloaded when the role runs.  The suggestion is to download them, do whatever it takes to believe they are correct, and then include them directly in the role.  This avoids automatically trusting the keys in the event the owncloud site is hacked, etc.

**Comment by ypid** [comment]
The [apt_key](https://docs.ansible.com/ansible/apt_key_module.html) might also come in handy: https://github.com/debops/ansible-owncloud/blob/370d90ebd6b6bc96be72cc0a8bb497f3f3759795/tasks/main.yml#L3-L7

**Comment by mikeashley** [comment]
This is fixed with the changes that happened in the move to Debian 8.

**Comment by ypid** [comment]
Hm, you mean [that apt_key task](https://github.com/sovereign/sovereign/blob/master/roles/owncloud/tasks/owncloud.yml#L20)? I am sorry to break it to you but that does not get you anywhere in terms of security. Please refer to https://github.com/nextcloud/vm/issues/11 (and excuse my harsh tone in that issue)

Ref: https://github.com/debops/ansible-owncloud/blob/bec00dfb5a56fe472e7d87aec900a864daad19c2/tasks/system_package_management.yml#L20

**Comment by mikeashley** [comment]
Appreciate the pushback.  I dug a little deeper and was surprised to see that the owncloud key is signed by the organization's build server key, and the signature path stops there.  It's true that if their infrastructure is compromised, they could upload new code, a new key, and nobody would be the wiser.

Unfortunately, I don't see a good way to validate their key.  A quick google for the key hashes didn't turn up anything.  We could download their key, but that would only tell us of a future key change.  Then, we wouldn't know if that's an intended key rotation or compromised infrastructure.

To me, this just adds support for dropping OwnCloud.

**Comment by ypid** [comment]
Thanks for the feedback.

> We could download their key, but that would only tell us of a future key change.

That would be something I think :wink: If that happens you could start to investigate.

> To me, this just adds support for dropping OwnCloud.

[Agreed](https://github.com/debops/ansible-owncloud/issues/45) :wink:
