### ISSUE TITLE
Configure services in a secure way.

### ISSUE THREAD

**Issue by ypid** [sovereign/sovereign#399]
See https://bettercrypto.org/
Related to #373.

Affected:

* Apache (Only TLS 1.2? Other enhancements …)
* OpenVPN (stronger RSA keys?)

**Comment by neuhaus** [comment]
This is an important topic, but to increase the chance of stuff getting done, please split it up into smaller issues, one per role.

This issue just refers to an ever-changing website and is too vague.

**Comment by ypid** [comment]
@neuhaus This was just something I noticed. I personally prefer how the DebOps project does things so I am not using sovereign. I opened issues for Apache and Postfix.
