### ISSUE TITLE
Rewrite OpenVPN role

### ISSUE THREAD

**Issue by ariddell** [sovereign/sovereign#401]
Since I need to use openvpn for another project, I thought I'd get started on this one. I think most of the needed changes are just systemd related (e.g., starting dnsmasq needs to be handled by systemd)

One thing I'm not sure about is where the openvpn firewall rules should be put. Is `/etc/rc.local` the place for them? Would putting them in `/etc/ufw/before.rules` make more sense? @jlund

For reference, this is the current rc.local

```
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#

iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -s 10.8.0.0/24 -j ACCEPT
iptables -A FORWARD -j REJECT
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

/etc/init.d/dnsmasq restart

exit 0
```

**Comment by conorsch** [comment]
Not sure if you're still working on this, @ariddell, but yes, `/etc/ufw/before.rules` is where I'd put the iptables rules. See here for an example: https://github.com/conorsch/ansible-digitalocean-vpn/blob/master/configure-server/files/ufw_before.rules

**Comment by ariddell** [comment]
Hi @conorsch, where does forwarding get enabled in your setup (e.g., the ``iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT`` line above) ? Any ideas about why dnsmasq is being restarted in the current sovereign setup (see above)?

**Comment by conorsch** [comment]
@ariddell The forwarding gets enabled here: https://github.com/conorsch/ansible-digitalocean-vpn/blob/master/configure-server/tasks/ufw.yml#L21 You're right that the role allows general forwarding of packets—that's a lazy hack, and precisely why I'm interested in getting a more stable and reusable role working as part of sovereign, so I can borrow it. =) 

Regarding the dnsmasq service restart, I haven't tested my role thoroughly for leakage, so let's test further before removing.

**Comment by neuhaus** [comment]
I suggest we close this issue until we have a PR, what do you think?

**Comment by conorsch** [comment]
@neuhaus @ariddell Consider this for inclusion: https://github.com/Stouts/Stouts.openvpn

It seems the pragma for sovereign is to commit roles directly to version control, rather than use submodules or galaxy requirements, so it may not be trivial to incorporate. That said, if it saves you any time writing custom openvpn logic, have at it!
