### ISSUE TITLE
Feature requests: Project Artillery, Tor support, SSH hardening

### ISSUE THREAD

**Issue by Andrew415** [sovereign/sovereign#404]
Please add https://github.com/trustedsec/artillery to complement fail2ban on all hosts. Admittedly it is sort of redundant to fail2ban but it contains a useful blacklist of attack nodes and obfuscates hosts actively used ports.

Tor support: I would love to see an optional runtime flag for making all (or partial) services accessible via a HiddenServer at build time.

SSH hardening see https://github.com/hardening-io/chef-ssh-hardening for an example of the right way to do it. I don't know of any existing ansible playbooks for this.

**Comment by spk** [comment]
https://github.com/hardening-io/ansible-ssh-hardening

**Comment by neuhaus** [comment]
When writing enhancement request (or bug reports), please put one issue/request in one bug report.

**Comment by neuhaus** [comment]
Need separate issues for this or they'll never get tackled.
