### ISSUE TITLE
Open-source Google Authenticator (Android App) is abandoned

### ISSUE THREAD

**Issue by ariddell** [sovereign/sovereign#411]
The open-source version of the Google Authenticator Android App is abandoned; Google is not incorporating upstream changes https://github.com/google/google-authenticator-android

Is this an issue for people? Is there something better on the horizon?

**Comment by vchuravy** [comment]
There is [FreeOTP](https://fedorahosted.org/freeotp/)

**Comment by ariddell** [comment]
To be honest, what really bothers me is that there's no way to turn it
off completely since it's nested inside roles/common and roles/vpn.  It
seems like it should have its own role.

I realize interdependencies among roles is not easy to manage with
ansible.

I'll close this for now. I suppose maintaining a
google-authenticator-free fork isn't much work at all.
