### ISSUE TITLE
Normalize role names

### ISSUE THREAD

**Issue by winks** [sovereign/sovereign#414]
Most roles are non-specific to their specific package being installed (e.g. `ircbouncer`, `blog` or `vpn`) but some are named like the software package they are using:

  * `owncloud`
  * `tarsnap`
  * `newebe`

Those should probably be called `filehosting`, `backup` and `socialnetwork` or something.

Addendum: owncloud is used for CalDAV, CardDAV and as filehosting, so maybe this needs to stay.

**Comment by al3x** [comment]
Perhaps we should just use the package names across the project?

**Comment by winks** [comment]
I've spent a lot of time working with puppet and the usual best practice is to have roles, profiles and components (more on this [here, for example](http://garylarizza.com/blog/2014/02/17/puppet-workflow-part-2/)

While this is overblown for this project (as it's not a whole infrastructure set of boxes) I think the idea of 'Profiles: technology-specific wrapper classes' and 'Roles: business-specific wrapper classes' is a good one, for example calling the role (ansible role now) `webserver` and not `apache`.

But this is nitpicking, and 'use package names' in this scope is perfectly fine as well, it should just be consistent :)

**Comment by nodiscc** [comment]
Hello, I am currently working on adding roles to sovereign (mostly web applications) and have come to the following conclusion: roles should be named after the software's name, in case there are several available alternatives for a particular role (eg. `mediawiki` and `dokuwiki`). An alias/default as the generic role name (eg. `wiki` defaults to `dokuwiki`) would also be welcome - I am very new to ansible and don't know if this is possible.

**Comment by ariddell** [comment]
I've seen people using the software/package name for the role name, e.g., https://github.com/CenterForOpenScience/cos-ansible-base/tree/master/roles

I'm still not sure about what the recommended approach is for dealing with "hard" interdependencies -- when two roles are interdependent, such as when one piece of software needs to modify another piece of software's config in some non-trivial way (apache makes this easy with conf.d directories but it's not always the case).

**Comment by neuhaus** [comment]
I concur with @nodiscc - if we name the roles after the software, it makes it easier to manage several alternatives.

**Comment by jplock** [comment]
I like this idea

**Comment by winks** [comment]
OK, so as people seem to agree on a naming scheme, the question is how to this in a non-breaking way.
I guess if you just cloned the repo and commented out some things in `site.yml` you're fine as long as you make sure to comment stuff that had been renamed as well. I think this would apply to most of the people using it.

**Comment by ariddell** [comment]
Could we just start with new role names in ``jessie``? I'm anticipating backing up the /encrypted directory and doing a fresh install.

**Comment by jplock** [comment]
I agree with @ariddell in that we should just update the `jessie` branch to the latest as that will eventually be merged into `master`.

**Comment by mikeashley** [comment]
Although I did not change existing module names, I did add guidance to `CONTRIBUTING.md` on the jessie branch.  See commit 37a85a8debf9dcfc8f9b53a08477f53e9eb9f907.
