### ISSUE TITLE
Nice to have: documentation how to migrate from an existing mailserver setup to sovereign

### ISSUE THREAD

**Issue by winks** [sovereign/sovereign#415]
Not sure if this is the right place, but I'll leave it for discussion.

While I think sovereign is mostly targeted at single individuals/small groups that want to host their own mail server et.al there's a use case for people migrating a bigger (but not really big) mail setup of, say 10-20 imap accounts and a few dozen aliases.

While there are some basic instructions to migrate a single account, there's nothing about the bigger scale things, and especially testing the spam filtering beforehand.

Right now I do plan to migrate, so if I find out stuff, I plan to document that.
Then again this might already play into full-on sysadmin mode and might be out of scope.

**Comment by neuhaus** [comment]
imapsync seems to be the most potent tool for migrating IMAP accounts.
I look forward to the documentation you plan to write.

**Comment by neuhaus** [comment]
Hi @winks, any updates on this?

**Comment by winks** [comment]
Sorry, blew off the migration for time issues and don't have any immediate plans unless my mail server magically self-destructs.

**Comment by neuhaus** [comment]
OK, I'll close it for now. Feel free to reopen it later on.
