### ISSUE TITLE
Roundcube database not created

### ISSUE THREAD

**Issue by m0rth** [sovereign/sovereign#417]
I am on a Debian 7 Wheezy 64bit KVM VM on Proxmox. I followed the exact steps from the Readme.
While running the Playbook I get following error:
```
NOTIFIED: [webmail | set roundcube password] ********************************** 
failed: [redacted.me] => {"changed": true, "cmd": ["sudo", "-u", "postgres", "psql", "-d", "roundcube", "-c", "ALTER USER roundcube with password 'redacted';"], "delta": "0:00:00.053525", "end": "2015-09-30 13:19:26.335245", "rc": 2, "start": "2015-09-30 13:19:26.281720", "warnings": []}
stderr: psql: FATAL:  database "roundcube" does not exist
```
When I run the playbook again, it doesn't fail at that point, but doesn't create the database.
I get the error "DATABASE ERROR: CONNECTION FAILED!", when I try to connect to Roundcube.

/var/log/postgresql/postgresql-9.1-main.log:
2015-09-30 13:19:26 UTC FATAL:  database "roundcube" does not exist

/var/log/roundcube/errors:
[30-Sep-2015 13:37:18 +0000]: DB Error: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "roundcube"
FATAL:  password authentication failed for user "roundcube" (GET /)

**Comment by vlow** [comment]
I have the same problem. Debian 7 Wheezy 64 Bit KVM VM on another hoster.

**Comment by KyleOndy** [comment]
I am having this issue on 64bit Wheezy VMs with both Linode and Digital Ocean.

    failed: [redacted.io] => {"changed": true, "cmd": ["sudo", "-u", "postgres", "psql", "-d", "roundcube", "-c", "ALTER USER roundcube with password 'not_my_password';"], "delta": "0:00:00.096447", "end": "2015-12-09 16:42:03.521714", "rc": 2, "start": "2015-12-09 16:42:03.425267", "warnings": []}
    stderr: psql: FATAL:  database "roundcube" does not exist

I could not get the database working with `sudo dpkg-reconfigure roundcube-core` under the deploy user,

**Comment by mikeashley** [comment]
This is addressed in the move to Debian 8.
