### ISSUE TITLE
How to administrate email accounts

### ISSUE THREAD

**Issue by libnull** [sovereign/sovereign#418]
Does Sovereign provide a command line tool to manage email accounts? Otherwise, if not, is it possible to run an web admin on top of it without compromising the installed setup?

Thank you!

**Comment by ariddell** [comment]
There's no command-line tool to manage email accounts. You have to edit the ``user.yml`` file.

**Comment by florianbeer** [comment]
I am successfully using http://www.vimbadmin.net to manage quite a few accounts and domains on a server that uses the same stack as sovereign. Sadly at the moment I wouldn't have any time to compile my own Ansible playbooks into a format that would work with this distribution (they are quite customized to my setup and not very modular).

**Comment by libnull** [comment]
Thank you both for the reply!

@florianbeer I will give Vimbadmin a try.

**Comment by neuhaus** [comment]
@libnull  How did it go with vimbadmin?
You can also try https://github.com/neuhaus/vea as long as you make sure it resides in a password protected area and is only accessible by trusted users.
