### ISSUE TITLE
Meeting at FOSDEM 2016

### ISSUE THREAD

**Issue by neuhaus** [sovereign/sovereign#420]
It'd be great to have a meeting of developers and users of this project at [FOSDEM 2016](https://fosdem.org/2016/) in Brussels, Belgium.
Please comment on this issue if you plan to be there.
We can try to get a room for the meeting if enough people sign up here.

**Comment by fengor** [comment]
I planned on being there but it is a 50:50 chance i won't be able to make it this year. If anyone stays around for CfgMgmtCamp afterwards I'd be up for a meet though

**Comment by spk** [comment]
I will be at FOSDEM 2016 and I'm interested

**Comment by neuhaus** [comment]
Great! I've contacted the organizers and asked if we can have a room for an hour or so. We can discuss sovereign, the direction it is taking and also answer questions for people who are new to the project.
If we can't get a room, I suggest we just meet at the Beer event on Friday night at the Delirium café.

**Comment by neuhaus** [comment]
The FOSDEM organizers replied: We can get a BoF room by reserving it at the event itself on Saturday morning.

**Comment by neuhaus** [comment]
I reserved the BoF room at FOSDEM for us for today, Saturday 18:00-18:30. 
See you there!

**Comment by neuhaus** [comment]
The room no. is H.3228
