### ISSUE TITLE
Disabling google authentication

### ISSUE THREAD

**Issue by shaneonabike** [sovereign/sovereign#421]
Hey folks

I was just going to write this on the wiki but I noticed that we don't have permissions.

For people who want to setup sftp for people to access their www folder you will need to disable the google authentication. Otherwise, programs like Filezilla won't cooperate and you will not be allowed access unless you setup a google authentication file.

Sooo... 

# Modify your PAM configuration

`sudo /etc/pam.d/sshd`
change `auth required pam_google_authenticator.so` by adding the ` nullok` at the end

Essentially, this tells the google authenticator to allow the login so that someone can setup google authentication.

Ref: https://github.com/google/google-authenticator/blob/master/libpam/README.md

**Comment by mikeashley** [comment]
I think it's a great idea to use the wiki to document some different uses of sovereign, especially multiuser deploys.  Are you still having trouble creating wiki pages?

**Comment by ariddell** [comment]
Perhaps there should be a variable which one can set to false somewhere (or perhaps the default should be to disable google authenticator?)

**Comment by mikeashley** [comment]
This discussion seems to have run its course.  I am going to go ahead and close this issue.
