### ISSUE TITLE
Apache doesn't serve http redirect

### ISSUE THREAD

**Issue by lukecyca** [sovereign/sovereign#425]
I'm finding that my blog isn't accessible via http, only via https. The intended behaviour is to issue a redirect to https, as well as a `Strict-Transport-Security` to tell the browser to use https for subsequent requests to the hostname. I suspect this hid the issue from me for a long time.

To test your own site: `curl -v example.com`. Expected behaviour is to get a 301 redirect, but actual behaviour is a 403 Forbidden.

I've isolated the issue to the status vhost used for monitoring apache, originally added last year by @philandstuff. If I disable that vhost, it works as intended again.

I have a handful of other local modifications, so I'd appreciate it anyone else can try reproduce this issue. This could be the issue that @almereyda was describing in #250.

**Comment by neuhaus** [comment]
Interesting. Can you run Apache in debug mode (parameter -X)?

**Comment by iboxifoo** [comment]
I found the solution at https://github.com/sovereign/sovereign/issues/360 fixed this particular issue.

**Comment by neuhaus** [comment]
Does changing fqdn.conf to "ServerName localhost" also fix the issue for you, @lukecyca ?

**Comment by lukecyca** [comment]
This is indeed a duplicate of #360.
