### ISSUE TITLE
Solr/Tomcat dependency in Debian Jessie

### ISSUE THREAD

**Issue by sread** [sovereign/sovereign#428]
In the jessie branch, I'm having trouble figuring out how to move forward with a solr problem I'm having in the testvm:

* In Debian 8: solr-tomcat depends on tomcat7
* In Ubuntu 14.04: solr-tomcat depends on tomcat6
* We pull in tomcat8 (a8a090573831c87abd233cdbcb5cbac822a2ba8d) but I can't get tomcat8 to sucessfully load the /etc/tomcat8/server.xml file introduced in b3dc1b00e9f50ab38c192e2efdcee04bcba50639

So I guess my question is why do we have a custom server.xml file at all (not clear from git history) and are we sure the version of solr in the repos (3.6.2) is compatible with tomcat8?

**Comment by neuhaus** [comment]
According to http://packages.ubuntu.com/xenial/solr-tomcat on Ubuntu 16.04 solr-tomcat (currently version 3.6.2+dfsg-8) will also depend on tomcat7.

**Comment by mikeashley** [comment]
PR #488 addresses this.
