### ISSUE TITLE
Consolidate database server installs and initial setup

### ISSUE THREAD

**Issue by cimm** [sovereign/sovereign#432]
Sovereign installs MySQL if I am correct but it looks like it doesn't touch the password for the `root` database user. The `root` user does not have a password by default in MySQL. Shouldn't we add a variable to set the `root` password during install?

**Comment by neuhaus** [comment]
It's been a while since I've done a fresh install, but doesn't the mysql-server package itself ask the user for a DB root password during install?

**Comment by nodiscc** [comment]
Ansible installs mysql-server unattended and doesn't ask for the root password. I was able to set the mysql root pw using these tasks https://github.com/nodiscc/srv01/blob/ansible/roles/apache2/tasks/apache2.yml#L81

**Comment by neuhaus** [comment]
A pull request is very welcome!

**Comment by mikeashley** [comment]
Database server setup has gotten sloppy in general.  Every module that needs a database assumes it has to set it up, and this leads to duplicated or inconsistent configuration.  The right thing to do is to move database server installs and initial setup to the common role.  The lack of an admin password for mysql can be addressed there.

Yes, a pull request would be welcome!

**Comment by neuhaus** [comment]
OK, postgres has been taken care of.
The only thing that still uses MySQL is OpenDMARC, and we want to get rid of having two DB servers so I don't expect the MySQL installation to move to the "common" roles, instead I think it will disappear. Closing. Thanks for the PR, @wsteitz !
