### ISSUE TITLE
Configure Apache to use only TLS 1.2

### ISSUE THREAD

**Issue by ypid** [sovereign/sovereign#442]
See https://bettercrypto.org/

* TLS 1.2
* Use regenerated DH parms. #373
* Other security related work, see https://bettercrypto.org/

Previous issue: #399

**Comment by neuhaus** [comment]
DH parameters are generated in pull request #441, however they are not yet used. See also issue #373 
Apache 2.2 - can't do it
Apache 2.4.7 (Ubuntu Trusty) - append dhparam to certificates
Apache 2.4.8 combined with OpenSSL 1.0.2+ enable a configuration directive.

**Comment by mikeashley** [comment]
I am considering this for jessie/xenial.  What are the actual changes being proposed?

**Comment by neuhaus** [comment]
Look at https://httpd.apache.org/docs/current/mod/mod_ssl.html search for "dh param"

**Comment by mikeashley** [comment]
Restating the scope of this suggestion, since using regenerated DH params is covered in #373.  At the moment, on jessie, the SSLProtocol configuration is `SSLProtocol ALL -SSLv2 -SSLv3`.

**Comment by mikeashley** [comment]
I am going to close this suggestion.  The current configuration under jessie supports TLS 1.0, 1.1, 1.2, which I think makes sense for backwards compatibility with clients.  I did a test against my server using https://www.ssllabs.com/ssltest/index.html and got good results (summary: A+ rating).
