### ISSUE TITLE
support for multiple domains and web gui for management?

### ISSUE THREAD

**Issue by andysaini** [sovereign/sovereign#447]
is it available?

**Comment by neuhaus** [comment]
You're not mentioning the services that you are interested in.

Apache can of course support multiple domains, for example using multiple virtual hosts.

Prosody also supports virtual hosts.

I'm assuming you are referring to email. The setup we use does support multiiple domains. There is no official GUI, I'm using [https://github.com/neuhaus/vea](VEA) myself.

**Comment by andysaini** [comment]
yes, I'm mainly interested in setting up multiple mailboxes for different domains.

**Comment by ariddell** [comment]
This is easy to do currently in ansible, look at the variable ``mail_virtual_users`` in ``user.yml``.

I'll close this. If there's interest in a GUI tool that should be a separate issue I think.

**Comment by neuhaus** [comment]
For those searching in old issues, the current location is now `mail_virtual_users` in `group_vars/sovereign`.
