### ISSUE TITLE
ufw tags needed on the firewall tasks

### ISSUE THREAD

**Issue by hvisage** [sovereign/sovereign#453]
Hi there,
 as I do my own firewalling and don't want ufw to interfere, I run the playbook with --skip-tags=ufw, but found several places that needs extra tags: ufw:

TASK: [xmpp | Set firewall rules for Prosody] *********************************
failed: [<host>] => (item=5222) => {"failed": true, "item": 5222}
msg: Failed to find required executable ufw

Places added: (grep -n ufw places):
roles/vpn/tasks/openvpn.yml:138:  tags: ufw
roles/xmpp/tasks/prosody.yml:46:  tags: ufw
roles/mailserver/tasks/dovecot.yml:93:  tags: ufw
roles/mailserver/tasks/postfix.yml:74:  tags: ufw
roles/ircbouncer/tasks/znc.yml:67:  tags: ufw

**Comment by jplock** [comment]
Would you mind submitting a pull request?

**Comment by hvisage** [comment]
Yes I do mind ;(
Bug me again in the new year then I’ll make some time to do the whole fork/etc. stuff (I’m a sysadmin, these gitting still gets to me …) 

> On 28 Dec 2015, at 5:13 PM, Justin Plock <notifications@github.com> wrote:
> 
> Would you mind submitting a pull request?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/sovereign/sovereign/issues/453#issuecomment-167586161>.
> 

---
Hendrik Visage
Envisage Systems / Envisage Cloud Solutions
084-612-5345 or 083-675-5506
hvisage@envisage.co.za
