### ISSUE TITLE
Roundcube outdated

### ISSUE THREAD

**Issue by mikeashley** [sovereign/sovereign#456]
The roundcube backport on wheezy is at 0.9.5 while the latest stable release of roundcube is 1.1.4.  Furthermore, the roundcube package has been dropped from jessie due to lack of maintainer support.  For compatibility across distributions I'm recommending we instead install from a released stable distribution instead of a package.

**Comment by neuhaus** [comment]
Ubuntu trusty is also at 0.9.5 btw

**Comment by mikeashley** [comment]
Yes, in April the major distributions will be running the same version again.  I've addressed the problem for me personally, so if we want to use packages, I am ok waiting until April.

**Comment by neuhaus** [comment]
Thank you!
