### ISSUE TITLE
domain aliases support?

### ISSUE THREAD

**Issue by strowi** [sovereign/sovereign#467]
hi,

i am just browsing through this project and couldn't find anything related... are domain aliases supported in the mail-configuration?
If not, it could be a nice feature addition as it is a quite commonly used feature...

regards,
strowi

**Comment by neuhaus** [comment]
We support the standard Postfix virtual domain stuff. There are three tables for this in the Postgresql database.
This could really use more documentation, pull requests welcome!

Does this answer your question?

**Comment by strowi** [comment]
sorry, for the late reply.. yes it does. 
Thank you very much!
