### ISSUE TITLE
encfs fails on Debian 8 without reboot

### ISSUE THREAD

**Issue by ariddell** [sovereign/sovereign#468]
On a Digital Ocean machine with a fresh Debian 8 image, encfs will not work without some extra intervention.

Is this a bug in Debian? Shouldn't installing the fuse package call `modprobe fuse` or whatever it takes to get things working?

If it's not a bug there needs to be some documentation in sovereign.

**Comment by jmcgnh** [comment]
I ran into this in the vagrant jessie development environment.

https://github.com/jmcgnh/sovereign/issues/9

My approach for dealing with it is to run modprobe fuse and check the stderr; the results indicate whether a reboot is needed. If needed, I do the reboot and wait for the system to come back. It's coded and tested, but I'm not satisfied that it's a worthy solution, yet.

**Comment by ariddell** [comment]
Checking modprobe and potentially exiting with an informative message sounds like a good solution.

**Comment by neuhaus** [comment]
@jmcgnh thanks for looking into this.

Since we're on the subject of disk encrption, should we investigate the use of [ext4 encryption](https://lwn.net/Articles/639427/) instead of encfs? It was added to Linux 4.1 so I expect that Ubuntu Xenial will have this feature in its kernel.

**Comment by ariddell** [comment]
@neuhaus that looks good. It looks like both encfs and ext4 leak the same information (# files, permissions, approximate sizes) but that ext4 is in the kernel and will enjoy, I would assume, a greater likelihood of long-term support.

**Comment by skriems** [comment]
I think encryption should totally be optional and no role should be dependant on that. My Server runs on an encrypted LVM volume (e.g.)...

**Comment by neuhaus** [comment]
Same here. Still, ext4 encryption is promising a speed improvement over encfs.

**Comment by mikeashley** [comment]
It looks like there are three options:

1. Continue with encfs and deal with a reboot.
2. Pick up the 4.1 kernel from backports and use ext4 encryption.
3. Use an encrypted LVM volume.

There are pros and cons with each choice.  Factors like performance, security, reliability, backups, and ease of setup should be considered.  Are there other factors that go in this list?  It would be great to see the tradeoffs side-by-side so we can decide which way to go with this issue.

**Comment by ariddell** [comment]
I vote to try ext4 in jessie and revert if it's worse than encfs. The fact that ext4 encryption is in the kernel tells me it's likely been audited more than encfs. It seems like there were some significant problems with encfs uncovered during the last audit: https://defuse.ca/audits/encfs.htm

**Comment by neuhaus** [comment]
@jmcgnh Do you think your solution in jmcgnh#9 is solid enough?

I like the idea of switching to ext4. I'm using an encrypted root partition myself so I'm not the expert on this one at the moment.
Note that the author of [ext4-crypt](https://github.com/gdelugre/ext4-crypt) commented that the kernel feature was "very unstable and experimental" 7 months ago.

**Comment by mikeashley** [comment]
I was not able to reproduce this in Debian 8.1 either in the vagrant test environment or on a fresh Linode instance.  Are you still seeing this problem?

For what it's worth, linode images do not include modprobe for security reasons.  @jmcgnh's patch won't work as is with that provider if we need it.

**Comment by mikeashley** [comment]
@ariddell Is this still a problem on Digital Ocean?  I'm not seeing any problems with it on Linode with Debian 8.1.

**Comment by ariddell** [comment]
I'll check. I'll be moving my install to jessie soon.

**Comment by ariddell** [comment]
Still happening.

**Comment by ariddell** [comment]
Problem is gone.
