### ISSUE TITLE
Update cgit to v0.12

### ISSUE THREAD

**Issue by neuhaus** [sovereign/sovereign#470]
Version v0.12 of cgit was released 8 days ago.
It appears to have lots of fixes.

If someone is using cgit a lot perhaps he/she can test it? If it works without a problem we only need to change `cgit_version` in `vars/defaults.yml`.

**Comment by mikeashley** [comment]
I upgraded my server to cgit 0.12 and gitolite 3.6.4.  Both seem to be working well.

**Comment by mikeashley** [comment]
Addressed on the jessie branch with PR #494.
