### ISSUE TITLE
Proposal: all PRs must first update jessie and only then update master

### ISSUE THREAD

**Issue by ariddell** [sovereign/sovereign#471]
There are important changes that got applied to master but didn't get applied to jessie. (I'm going to attempt a rebase today.)

In light of this, would it be useful to have a public timeline for switching to jessie as the default branch? April is the release of Ubuntu Xenial.

What's a good solution in the short term? Would requiring that PRs apply to both branches be useful? Or should someone just make sure to rebase every month?

**Comment by ariddell** [comment]
I've rebased jessie and pushed it to this branch here: https://github.com/ariddell/sovereign/tree/jessie-rebased

I'm not sure exactly how you review a rebase. Would it be preferable to just cherry-pick each commit from master separately and submit that as a PR?

**Comment by ariddell** [comment]
I'll answer my own question. All the changes in master that are missing from jessie need to be submitted as individual PRs against jessie. I'll get started on this.

**Comment by neuhaus** [comment]
Thanks for doing this!
Ideally we would do a rebase every now and then and once we officially support Jessie, the jessie branch turns into the master branch, the former master branch moves to the wheezy branch and only gets maintenance updates until we drop it.

Please make sure that these patches don't break compatibility with Ubuntu Trusty.

**Comment by ariddell** [comment]
I've done a few of the cherry-picks. I'll keep going. Thanks for
the note.

My sense was that the jessie branch was just going to support jessie and
the next Ubuntu (jessie-based) LTS. In any event, it's a question for
another issue. I'm going to just cherry-pick the useful commits in the
master branch here.

**Comment by neuhaus** [comment]
Nah, I thought the jessie branch was a temporary thing until it's working and then we can merge it into master.
If the jessie branch breaks backward compatibility with older distributions we need to move the last working code into a maintenance branch so people have some time to upgrade their stuff

**Comment by ariddell** [comment]
I thought the consensus was to break backward compatibility. I'm clearly wrong! Not sure where this is best discussed. Probably not in an issue tracker. Maybe a mailing list?

**Comment by neuhaus** [comment]
There is no mailing list, this is the right place for discussion.

Sure, jessie can break backward compatibility. That's why we need another branch for the phase where we support both jessie and something older.

**Comment by ariddell** [comment]
Ok, so at some point we create a branch called `oldstable` and rename
jessie to master? Works for me.

**Comment by neuhaus** [comment]
exactly. that point is reached as soon as the current jessie branch is stable.

**Comment by ariddell** [comment]
Ok, I've cherry-picked everything #476. @neuhaus, mind having a look?

**Comment by neuhaus** [comment]
I will once I get back home
