### ISSUE TITLE
Document mirror autoselect behavior in ubuntu

### ISSUE THREAD

**Issue by simontretter** [sovereign/sovereign#485]
I don't know how many sovereign installations run Ubuntu. For me, the mirror autoselect keeps breaking my installation in weird ways. ansible does not run through because of some apt error, mostly because the apt source is not giving me what I need. 

Can't we just leave this on the standard mirror the hoster provides?

**Comment by neuhaus** [comment]
Are you running Ubuntu trusty? What is the exact problem you encounter? I haven't had any problems with the mirror autoselect.

**Comment by simontretter** [comment]
It often gives me broken mirrors where apt-get update won't run through. If I fix the sources.list by using official mirrors, everything runs fine.

**Comment by neuhaus** [comment]
I see. What do you suggest we do? We could add this problem and its solution to the documentation.

**Comment by simontretter** [comment]
That would be one way. I personally would be fine without the mirror autoselection. Would dropping it hurt anyone?

**Comment by neuhaus** [comment]
Fine with me, as long as the documentation is clear about it.

**Comment by ariddell** [comment]
Can we just have a default variable in the role that one can turn on or off?

**Comment by neuhaus** [comment]
:+1:

**Comment by neuhaus** [comment]
@simontretter can you give some examples of the apt error messages you encounter due to mirror autoselect? It seems you're the only one hitting this bug.

**Comment by neuhaus** [comment]
I'm closing this until @simontretter provides us with some actual error messages
