### ISSUE TITLE
OpenDMARC fails to install (jessie)

### ISSUE THREAD

**Issue by mikeashley** [sovereign/sovereign#491]
The database import fails to run.  There is a syntax error in the import file, and after that is fixed, there is type error.  It appears the import file was written for a database other than postgres.

It looks like this broke at commit 2352d2d67e591cb1ee841c0782ea7ce05b36e355.  Speculation: the aim of the commit was to remove the last(?) reference to mysql.

**Comment by mikeashley** [comment]
I would like @al3x to weigh in on intent.  Some brief googling fails to turn up how to configure this to use postgres, and the man pages are all about mysql for report generation.  Seems like the two options are 1) drop opendmarc, and 2) revert to using mysql and install it.

**Comment by al3x** [comment]
Yes, I was in the process of removing MySQL. It seemed to bother users that they were running two databases (understandably).

**Comment by mikeashley** [comment]
I found Issue #397 where this has come up before.  I recommend reverting to MySQL so that it works and that we can keep moving towards a stable jessie branch.  If somebody feels strongly about squashing MySQL from the system, they can tackle making it work with Postgres separately.
