### ISSUE TITLE
Support roundcube

### ISSUE THREAD

**Issue by mikeashley** [sovereign/sovereign#495]
Roundcube support needs to be reinstated from Debian backports and tested.  We've had nagging installation problems (#417 is the latest) under wheezy.  Is the situation any better under jessie, or do we need to consider a different install method?

**Comment by neuhaus** [comment]
For the record, the [version](https://packages.debian.org/en/jessie-backports/roundcube) available via jessie-backports (1.1.4) is the same that Ubuntu Xenial [will ship with](https://launchpad.net/ubuntu/xenial/+source/roundcube).

**Comment by neuffer** [comment]
Current roundcube in Debian testing is1.2.0+dfsg.1-1

**Comment by mikeashley** [comment]
Addressed with PR #590.
