### ISSUE TITLE
dovecot auth error after playbook completion

### ISSUE THREAD

**Issue by Anonymouslemming** [sovereign/sovereign#499]
I've deployed a new host with just the following roles:
`  roles:
    - common
    - mailserver
    - webmail
    - git
    - monitoring`

After deployment completes, I see that services are running as expected, but I cannot login. The following logs has the actual mail address replaced by the values from my playbook for clarity:

`Feb 18 17:09:47 sovhost dovecot: auth: Error: LINE 1: SELECT email AS user, password FROM virtual_users WHERE emai...
Feb 18 17:09:47 sovhost dovecot: auth: Error:                                             ^
Feb 18 17:09:47 sovhost dovecot: auth: Error: pgsql: Query failed, aborting: SELECT email AS user, password FROM virtual_users WHERE email = '{{main_user_name}}@{{domain}}';
Feb 18 17:09:47 sovhost dovecot: auth: Error: sql({{main_user_name}}@{{domain}},my.mailclient.ip,<MPB2nhIsVgBRinWu>): Password query failed: ERROR:  relation "virtual_users" does not exist
Feb 18 17:09:47 sovhost dovecot: auth: Error: LINE 1: SELECT email AS user, password FROM virtual_users WHERE emai...
Feb 18 17:09:47 sovhost dovecot: auth: Error:                                             ^
Feb 18 17:09:49 sovhost dovecot: imap-login: Disconnected (auth failed, 3 attempts in 26 secs): user=<ms@q{{main_user_name}}@{{domain}}>, method=PLAIN, rip=my.mailclient.ip, lip=sov.host.ip, TLS, session=<MPB2nhIsVgBRinWu>`

If I connect to the mailserver database using the postgres user, I cannot see any tables:
`mailserver=# \d
No relations found.`

I did have one failed  task related to encfs when running the play:
`PLAY RECAP *********************************************************************
sovhost                     : ok=186  changed=143  unreachable=0    failed=1`

`TASK [common : Check for existing encfs] ***************************************
fatal: [sovhost]: FAILED! => {"changed": false, "cmd": "ls /encrypted/*", "delta": "0:00:00.004261", "end": "2016-02-18 22:41:39.514355", "failed": true, "rc": 2, "start": "2016-02-18 22:41:39.510094", "stderr": "ls: cannot access /encrypted/*: No such file or directory", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring`

Is this the cause, or is there something else that I'm missing here ?

**Comment by ariddell** [comment]
What version of ubuntu or debian?

**Comment by Anonymouslemming** [comment]
Ubuntu 14.04.4 LTS

I've tried ansible installed from pip (2.0.0.1) and from github (2.1.0) with the same results.

**Comment by mikeashley** [comment]
You may have misconfigured `vars/user.yml` and/or accidentally modified `vars/defaults.yml`.

This is telling: `Feb 18 17:09:49 sovhost dovecot: imap-login: Disconnected (auth failed, 3 attempts in 26 secs): user=<ms@q{{main_user_name}}@{{domain}}>, method=PLAIN, rip=my.mailclient.ip, lip=sov.host.ip, TLS, session=<MPB2nhIsVgBRinWu`.

The string `{{main_user_name}}@{{domain}}` should have been replaced with your main user name @ your domain.  Also, in `vars/user.yml` that string normally is `{{ main_user_name }}@{{ domain }}`.  (Not sure if the space between the braces and the variable name is required by Ansible.)

I recommend double-checking your configuration.

**Comment by Anonymouslemming** [comment]
Sorry if I didn't make it clear in my post - that was my clumsy attempt to obfuscate my domain details. I'm definitely seeing the value I put for main user and domain in the user / domain parts in the log.

**Comment by mikeashley** [comment]
There has not been followup on this bug report, so I am going to assume it's been resolved.
