### ISSUE TITLE
Proposal: add a contributor to sovereign

### ISSUE THREAD

**Issue by ariddell** [sovereign/sovereign#501]
@mikeashley has done an epic amount of high quality work on the Let's Encrypt scheme/role and on getting the jessie branch working. I'd like to propose that he be made a contributor to sovereign.

cc: @al3x, @lukecyca, @neuhaus, @jplock

**Comment by jplock** [comment]
+1

**Comment by neuhaus** [comment]
:+1:

**Comment by mikeashley** [comment]
Thank you for the recommendation and endorsements.
