### ISSUE TITLE
Run opendmarc reporting with postgres as the back end

### ISSUE THREAD

**Issue by mikeashley** [sovereign/sovereign#502]
The opendmarc package uses mysql as the back end.  If the installation could be modified to use postgres, this would allow sovereign deploys to avoid installing mysql.  There was a brief discussion around this in the comments on PR #397.

**Comment by neuhaus** [comment]
This would also fix issue #497 if it were done on trusty (it's not an issue for xenial).

**Comment by ariddell** [comment]
What needs to be done to make this happen. It would be a positive development if only postgres were required.

**Comment by mikeashley** [comment]
At a minimum the SQL to initialize the database needs to be converted from MySQL to PostgreSQL, and the package needs to be configured to use posgres as the backend.  Nominally it supports this, since the backend support looks abstracted, but I don't recall seeing anything to suggest that this had ever been tested or is supported.

**Comment by sorki** [comment]
I've created an experimental fork of opendmarc with PostgreSQL support (only)

https://github.com/nestihacky/opendmarc

Commit: https://github.com/nestihacky/opendmarc/commit/0241bf1999706b197ccb021da75a921bbc38233f 

I also have packages for Fedora/Centos if you would like to test it: https://copr.fedorainfracloud.org/coprs/rmarko/opendmarc/

I'm only running this for few days in production. It still needs a number of IF clauses to handle both MySQL and PostgreSQL, bit more testing and then I'll try to upstream this.

Btw we now have usable mailserver deployment scripts based on sovering mailserver that targets Centos 7 - https://github.com/nestihacky/ansible-role-mailserver

**Comment by neuffer** [comment]
what is the status on this issue? 
Would it be possible to use opendmarc with postgresql via the libopendbx1-pgsql backend?

**Comment by mikeashley** [comment]
Addressed in PR #720.
