### ISSUE TITLE
Support upgrading in vpn role

### ISSUE THREAD

**Issue by Yannik** [sovereign/sovereign#515]
Hi,
maybe it would be prudent to add another task to #512 / #511 which deletes `/etc/rc.local` or deletes the iptables which were present in it in the previous version of sovereign? The current tasks do not cause issues if these iptables commands are in the rc.local, but it would be nice to actually clean it up.
Are there any procedures that exist for things like this in sovereign? Like introducing such a task which is necessary for upgrades but not for fresh setups in a minor version and remove one or two major versions of sovereign later?

**Comment by ariddell** [comment]
Something easy would be to abort (I think there's a ``fail`` module) if a file is present and prompt the user to delete the file.

**Comment by mikeashley** [comment]
I like the idea of using Ansible to upgrade installs, but I worry about confusion for users and burden on playbook authors.  If I'm using sovereign, can I count on a playbook to handle the upgrade for me or not?  For authors, how do I reason about upgrades?  How do i test?  How far back do I take support?

When we moved to Jessie, the approach was to do a clean break: assume the user is doing a clean install.  That said, we have a wiki page for those of us who are upgrading to call out what to watch for and how to fix the one-off bumps in the upgrade path.

**Comment by ariddell** [comment]
Clean break sounds best to me as well. I think this is safe to close for now.
