### ISSUE TITLE
Remove OpenDKIM milter from postfix configuration

### ISSUE THREAD

**Issue by mikeashley** [sovereign/sovereign#529]
Rmilter can implement domainkeys identified mail (DKIM).  Currently OpenDKIM is used to implement it in Sovereign.  We use Rmilter for Rspamd, so I suggest removing the opendkim package and using Rmilter instead to simplify the mailserver setup.

**Comment by carljm** [comment]
+1. Rmilter's DKIM support still requires OpenDKIM under the hood (though maybe just a library package, I haven't looked into details yet), so we won't be totally removing opendkim, but it will mean one less milter postfix has to talk to.

**Comment by vstakhov** [comment]
BTW, in the upcoming Rspamd 1.4 and Rmilter 1.10, it is intended to use Rspamd to add [DKIM signatures](https://rspamd.com/doc/modules/dkim.html) than Rmilter. 

The same is also true for all other functions of Rmilter: [ratelimits](https://rspamd.com/doc/modules/ratelimit.html), [greylisting](https://rspamd.com/doc/modules/greylisting.html), [replies](https://rspamd.com/doc/modules/replies.html) and even antivirus scanning - that's all now in Rspamd.

I plan to add milter protocol support directly to Rspamd (perhaps, in 1.5), so Rmilter won't be needed any longer.

**Comment by mikeashley** [comment]
I took a cursory look at switching to rspamd for dkim signing and verification.  It looks like verification works out of the box.  For signing with multiple domains, some Lua scripting is required.  An example script is given in the module documentation.  To remove OpenDKIM, rspamd's dkim module configuration would need to be updated and DKIM signing tested.

I could take a stab at this.  Does anybody know of a good way to inspect headers on outgoing email (to verify DKIM signing happens)?

**Comment by nangia** [comment]
Perhaps https://mailcatcher.me or https://github.com/mailhog/MailHog can help you inspect headers.

**Comment by mikeashley** [comment]
Addressed in PR #720.
