### ISSUE TITLE
Upgrade to Ansible 2.0

### ISSUE THREAD

**Issue by ariddell** [sovereign/sovereign#538]
The Ansible 2.0 refactor was significant. It would be useful to have a version of sovereign that's compatible with the current version of ansible.
- [ ] Get Ansible 2.0 running in the jessie branch
- [ ] Revert workarounds for pre-ansible 2.0 (#534 ?)

**Comment by neuhaus** [comment]
This issue is getting more important, Xenial ships with Ansible 2.0
