### ISSUE TITLE
Step by step installation guide.

### ISSUE THREAD

**Issue by itsazzad** [sovereign/sovereign#539]
How can I install the system in the server?
I have tried following https://github.com/sovereign/sovereign/wiki/Setting-up-on-DigitalOcean-with-Debian-7-(INCOMPLETE) but here I am getting confused with the local and production server. 
Is there any clear instructions available?

**Comment by neuhaus** [comment]
The installations instructions are in the [README](https://github.com/sovereign/sovereign/blob/master/README.md).

You need to have a basic Debian or Ubuntu server installation before you can start with Sovereign. Pretty much all you need is the ability to SSH into the machine and run `sudo`.

The local box where you start ansible can be anything really.. you can even run Ansible on the destination server itself.

Please elaborate on the problem you are having.

**Comment by itsazzad** [comment]
@neuhaus I had tried with the readme first but the first step it is saying `1. Get a wildcard SSL certificate` where its using the file `roles/common/files/wildcard_private.key` but that file and folder is not yet available. From here starts the confusion.

**Comment by neuhaus** [comment]
OK, thanks for clarifying that. You pointed out a valid point:
The README (mistakenly) assumes that you have already downloaded the project files and unpacked them.
You can do so by clicking the "Download ZIP" button on the [project page](https://github.com/sovereign/sovereign). It links to https://github.com/sovereign/sovereign/archive/master.zip

**Comment by neuhaus** [comment]
@itsazzad Did that clear up the issues you have or is there still something that's unclear?

**Comment by itsazzad** [comment]
Sorry, project was cancelled. Before that I went with `Mail-in-a-Box` only because of the wildcard SSL. Next time if need may try with `sovereign` again.
