### ISSUE TITLE
Suppress 'Authenticated Sender'-Header?

### ISSUE THREAD

**Issue by strowi** [sovereign/sovereign#540]
Hi,

i have a couple of Alias-Domains setup under a single account. Occasionally i need to send emails from those domains (which works fine with the current sovereign setup;)).
But while i was checking for valid DKIM Headers i found out, that there is a Header injected containing the original Account email:

sovereign account/login: romain@xyz.de
Then i send email from roman@aliasdomain.de:
And i get a Header showing my account:
```
Received: from [127.0.0.1] (localhost [127.0.0.1])
	(Authenticated sender: romain@xyz.de)
	by mail.hasnoname.de (Postfix) with ESMTPSA
	for <roman@recipient>; Mon, 21 Mar 2016 21:35:39 +0100 (CET)
```

I'm still trying to figure out if this is injected by postfix, fuglu but maybe someone knows the origin?
 
greetings,
Roman

**Comment by neuhaus** [comment]
I don't see that part in my Received header, I may have changed something in my setup though.

An example mail header looks like this:

    Received: from [127.0.0.1] (localhost [127.0.0.1])
	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))
	(No client certificate requested)
	by mail.example.com (Postfix) with ESMTPSA id A2520C002BC
	for <user@example.com>; Thu, 24 Mar 2016 15:33:03 +0100 (CET)

**Comment by neuhaus** [comment]
See also https://askubuntu.com/questions/78163/when-sending-email-with-postfix-how-can-i-hide-the-sender-s-ip-and-username-in

You may want to set

    smtpd_sasl_authenticated_header = no

in `/etc/postfix/main.cf`.
The thing is, this option defaults to "no" and we do not have it in our template so I don't understand why it even shows up for you.

I'll close the bug for now, feel free to reopen.
