### ISSUE TITLE
SSH Error: Permission denied

### ISSUE THREAD

**Issue by scouseman** [sovereign/sovereign#556]
Hi, Hi am am very new with linux so please bare with me, I have managed to set up my ssh connection so I can login to my server with putty and do not require to enter a passwword, but when I try and run the script I get the following error:

![scree](https://cloud.githubusercontent.com/assets/12296640/15000674/7e8264ae-1189-11e6-9bf2-7d5044b18803.JPG)

Anyone any ideas what I could be doing wrong? Cheers

**Comment by mikeashley** [comment]
This appears to be a basic setup problem with your server.  I recommend you check your hosting providers documentation and make sure you can login from a shell via SSH.
