### ISSUE TITLE
OpenDMARC cron failing

### ISSUE THREAD

**Issue by tomasbedrich** [sovereign/sovereign#557]
I am using Debian Jessie and everything is working fine, except of this cron task, which is failing. Here is the log:

```
opendmarc-import: started at Fri May  6 01:00:02 2016
opendmarc-import: connected to database
opendmarc-import: terminating at Fri May  6 01:00:02 2016
opendmarc-reports: started at Fri May  6 01:00:03 2016
opendmarc-reports: failed to collect domain names: Table 'opendmarc.requests' doesn't exist
opendmarc-import: started at Sat May  7 01:00:01 2016
opendmarc-import: connected to database
opendmarc-import: terminating at Sat May  7 01:00:01 2016
opendmarc-reports: started at Sat May  7 01:00:02 2016
opendmarc-reports: failed to collect domain names: Table 'opendmarc.requests' doesn't exist

**Comment by mikeashley** [comment]
I am not seeing that on my server.  Perhaps replay the mailserver playbook with the dmarc tag and see if there is anything strange?  From the log it looks like the database is misconfigured.

**Comment by tomasbedrich** [comment]
Replaying the playbook with `--tag=dmarc` completed successfully and gave me this result:

```
...
PLAY RECAP *********************************************************************
ok=31   changed=0    unreachable=0    failed=0
```

Nothing was changed and everything seems to be okay from the perspective of playbook.

I was digging a little bit deeper and opened the MySQL DB and *it was empty* - so even after replaying the playbook, the schema hasn't been created. Therefore I have created the schema manually using `mysql -u opendmarc -p < /usr/share/doc/opendmarc/schema.mysql` and it works now.

The DB was empty - my fault, I know. But I think there is also a problem with the playbook, more concretely [with this line](https://github.com/sovereign/sovereign/blob/jessie/roles/mailserver/tasks/opendmarc.yml#L29). The notify handler won't execute unless DB is created so *the schema cannot be re-created separately*. What do you thing about separating the schema import task?

**Comment by carljm** [comment]
I made that change. Previously the schema always re-imported on every run. 

Ideally the schema import would be a task that runs conditionally based on a more detailed check (like, does the database exist, or do the tables exist). The ideal check would be for a complete schema match, not sure that's feasible.

Anyway if you're able to put together a PR along those lines I'd be in favor, but I don't think we should go back to "schema import always runs unconditionally."

**Comment by carljm** [comment]
Probably what happened in your case was that an Ansible run crashed after creating the db but before handlers were run.

**Comment by mikeashley** [comment]
I agree with @carljm.  We shouldn't run the import script unconditionally.  I've seen such import scripts unconditionally drop tables if they already exist.  This would not be good if replaying a playbook on a system that has been running for a while.

Before making a change, we should understand what really happened.  Can the problem be reproduced in a test setup?

**Comment by carljm** [comment]
I am 95% sure that my guess above about what happened is correct. It's a general problem with Ansible handlers. If a later task fails and the Ansible run aborts before running handlers, the handlers won't ever run (because the task that triggered them won't report changed next time). Moving away from using a handler for this would take care of that.

**Comment by tomasbedrich** [comment]
Sorry for the delayed reply, guys. I cannot confirm what actually happened, but I think @carljim is correct. The [OpenDMARC schema](http://apt-browse.org/browse/ubuntu/trusty/universe/amd64/opendmarc/1.2.0+dfsg-1/file/usr/share/doc/opendmarc/schema.mysql) is using `IF NOT EXISTS` clauses, so what's the problem of running it unconditionally? The SQL engine will handle the potential conflict.

**Comment by neuhaus** [comment]
I was going to suggest using `IF NOT EXISTS` for the schema statements - if it already uses them I see no harm in doing them on every playbook invocation.

**Comment by carljm** [comment]
I don't like it because it makes the play report "changed" every time; I couldn't find a way to properly detect changed status. Also it's slower :/

**Comment by tomasbedrich** [comment]
Ok, I understand your opinion. At least it might be interesting [to rewrite the playbook using `register` keyword](http://stackoverflow.com/a/28840013/570503) to minimize the time between creating the DB and running the import.

Another option would be to write a script which would do the import, count a number of created tables and return an appropriate exit code for ansible, which would handle it using `changed_when` keyword. But honestly, I have no idea, how to "cleanly" count the number of created tables.

**Comment by nfedyashev** [comment]
@tomasbedrich thanks for the workaround
