### ISSUE TITLE
Allow users to change their passwords independently

### ISSUE THREAD

**Issue by oskapt** [sovereign/sovereign#581]
The way that the playbook is designed appears to target a single-user environment. All passwords are generated manually offline, most are hashed, and the hashed form is put into the config. These hashed forms are inserted into files and tables as appropriate.

At the same time, the mail portion of the configuration allows (and encourages) multiple users. Sovereign, as built, is an excellent setup for a private mail server. The problem is that users cannot change their passwords.

As it is currently written, with all passwords are stored in the Ansible configuration, all Postfix tables are dropped and recreated on every Ansible run. This means that even if a user _could_ change their password, it would be reset on the next run. If that structure changes, there is still no provision for a user to change their password. The would have to come to the person who runs Ansible, tell them the new password, and that person would have to generate the new hash and re-run Ansible.

This is contrary to our responsibilities as system administrators. We should _not_ have everyone's password. Users should trust that the system we run is secure. We should encourage people to change their passwords on first login so that we have plausible deniability regarding access to anyone's account, whether they be friend, family, or coworker.

My proposition is as follows:

1. Configure the SQL in a way that does not drop and recreate the tables. We can do this by using `IF NOT EXISTS` statements, conditionals around index creation, and dynamic SQL around creating and removing users based on whether they exist already and what we are telling Ansible the state of the user should be (`enabled: yes` or something similar).
2. Add a flag of `force: yes` to the user configuration in Ansible that tells it to overwrite the current password with the provided hash. This can be used for password resets and locking accounts that we want to keep around. Those people who wish to continue using Sovereign in its current form can provide `force: yes` to all account definitions.
3. Add additional configuration to Roundcube to enable the `password` plugin and provide the appropriate SQL statements for it to work with Postgres.

**Comment by neuffer** [comment]
Additionally I'd suggest the use of postfixadmin.
Ubuntu and Debian currently have version 2.93-2 in their repositories.
Postfixadmin is under active development even so it doesn't look like it from the projects webpage.

**Comment by mikeashley** [comment]
This has come up several times in the past.  As we say in the first paragraph of this project's README, sovereign is designed for maintaining personal cloud services.  I do not recommend it for groups precisely because all configuration information is kept on the client side, under version control, including passwords.

Admittedly, not all our roles are in line with this design intent.  OwnCloud is an example.  However, I'd rather keep the pressure on having the complete configuration on the client side and not go in the wrong direction.

[mailinabox.email](http://mailinabox.gui) has a gui.  Perhaps it has these features that you are looking for as well?

**Comment by oskapt** [comment]
My philosophy is covered in #582 in today's response.

As for keeping thing on the client side, such as passwords, and in a repo, Ansible Vault is designed to allow you to do this safely. 

Furthermore, if the use case _can_ spread to > 1 user (even if that is just me and my wife), why not give users the ability to change passwords? Does including this functionality, already nicely packaged for you, cause damage?

I can see where this is headed. I provide solutions to problems in this project, and you direct me to another project instead. Might as well just tell me to use Gmail.
