### ISSUE TITLE
Rerunning the mailserver role exposes a race condition

### ISSUE THREAD

**Issue by oskapt** [sovereign/sovereign#582]
As an extension to the behavior documented in #581, there is a race condition regarding mail delivery when the playbooks are run. 

During the time that the SQL is being run, any mail that is delivered or being processed will suddenly find itself with no user configuration on which to operate. The period in question is small, but it exists.

The problem arises from our behavior of dropping the tables and recreating them from scratch.

My proposal is that we don't do this. If we were running mailservers without using Ansible, we would have a utility for managing users and domains, executing add/move/change as necessary. No Exchange admin blows away the database and reloads all configuration from a CSV file when he wants to add a new user. Even those using flat file maps make changes and recompile the hashed versions. The mere fact that we are using Ansible does not mean we suddenly have license to be sloppy. If anything, we should be _more_ elegant, because our CLI-fu gives us more flexibility.

Dropping the tables on every run is the easy way out, but it's not the right way to do it. Dynamic SQL templates, though more complicated, deliver precision actions according to the rules we define.

My solutions proposed in #581 will solve this issue because Ansible will only act on objects that need to change. If we decide not to implement the `password` plugin in Roundcube, then we can assume that the user has never changed his password. If that assumption is true (and without providing a means for them to do so, it is true), then we only have to make add/move/changes to the database records for users and domains that require them. Our exposure is then no more than it is in an enterprise environment when the admin clicks the OK button in the GUI.

**Comment by mikeashley** [comment]
Why wouldn't you simply stop the postfix and dovecot services before commencing with configuration changes?  That seems to be the cleanest way to handle it.

**Comment by oskapt** [comment]
Configuration management (Ansible, Puppet, Chef, cfengine) is a tool to automate tasks that a human would do. It does them in the same way, every time, without fail. When I write playbooks, I automate myself.

- No human system administrator stops the mailserver when adding users.
- No human sysadmin blows away the entire database every time they want to add a user, domain, alias or other object.

To do so is wrong. It's lazy. It's forgivable only in the context of trying to get to our objective as quickly as possible, but if a problem comes up as a result of this decision, we are tasked with reworking the solution to fix the problem. 

If you only care about a mailserver serving mail for yourself, then you are justified in not caring. However, this does not preclude considering a better solution. Sovereign's mailserver and webmail component _already_ build and configure a complicated group of applications, so rather than reinvent the wheel, people _will_ use this for small groups. You can continue to tolerate its shortcomings under the pretense of "it was never meant to be used by more than one person," but Postfix, Dovecot, Roundcube, et al, _were_ meant to be used by more than one person. 

I'm offering a solution that keeps the workflow clean and professional. You can decline to accept it, but do it for a reason better than, "why would you not just simply take the lazy, easy, amateur way out?"
