### ISSUE TITLE
z-push failing on trusty

### ISSUE THREAD

**Issue by oskapt** [sovereign/sovereign#583]
Fresh install on Trusty is throwing this error:
```
10/08/2016 09:36:51 [17106] [FATAL] [user@foo.com] FatalException: BackendIMAP(): php-imap module is not installed - code: 0
```

As a result, mobile devices (all my iDevices) won't connect and won't process mail in or out.

**Comment by oskapt** [comment]
I just rewrote the config to install z-push from package (they now have package repos), hoping that 2.3 would fix this issue. It doesn't, so now I'm diving into their code to see where the function they're testing actually resides. Either it's not in `php5-imap` (which we install) or the name has changed (which they should have caught).

**Comment by oskapt** [comment]
Hrmph. Nevermind. On Trusty we need to call `php5enmod imap` to actually turn it on after installing. PR forthcoming.

**Comment by mikeashley** [comment]
Closing, since the PR covers this.
