### ISSUE TITLE
letsencrypt-gencert script not found

### ISSUE THREAD

**Issue by doughock** [sovereign/sovereign#599]
My install is errors out on

`TASK [common : Get an SSL certificate for {{server name}} from Let's Encrypt] ***`

When I attempt to start apache2 manually on the server  I get the following error:

```
AH00526: Syntax error on line 9 of /etc/apache2/conf-enabled/ssl.conf:
SSLCertificateKeyFile: file '/etc/letsencrypt/live/{{server name}}/privkey.pem' does not exist or is empty

```
**{{server name}} is a redaction for posting.**

I check under the letsencrypt directoy that is created from the LetsEncrypt release download (`letsencrypt.yaml`).  I don't see a `letsencrypt-gencert` file.

Thanks in advance for any assistance.

**Comment by doughock** [comment]
It seem to be an issue with the server name.  I change the name to something more simple (i.e. domain.com) and the installation finished.

**Comment by neuhaus** [comment]
OK, can you tell us what characters caused the issue in the hostname? Perhaps we can add a little note to the README regarding invalid hostnames.
