### ISSUE TITLE
Can you help me decode the error?

### ISSUE THREAD

**Issue by working-name** [sovereign/sovereign#600]
TASK [mailserver : Ensure mail domain directories are in place] ****************
fatal: FAILED! => 
```json
{
   "failed":true,
   "msg":"the field 'args' has an invalid value, which appears to include a variable that is undefined. 
The error was: 'unicode object' has no attribute 'name' The error appears to have been in 
'sovereign/roles/mailserver/tasks/dovecot.yml': line 24, column 3, but may be elsewhere in 
the file depending on the exact syntax problem.

The offending line appears to be:
- name: Ensure mail domain directories are in place  ^ here"
}
```

From what I can gather there's supposed to be directories for the domain name and the account name inside /decrypted. Right now I only have "test" in there. I cannot find another reference to `item.domain` and `item.account` which are probably the "undefined variables".

Should I create the folders manually? Will that backfire on me?

I've been attempting this on 14.04, then 16.04, and now I'm on 15.04 which seems to work the best so far. I did have to hack another spot in the postfix_main.cf template where it tried to pull `.join(friendly_networks)` but `friendly_networks` is a blank field.

**Comment by neuhaus** [comment]
Are you using the master branch or the wheezy branch from git?

**Comment by working-name** [comment]
Hi there,

I was using the master, I wasn't aware there was a wheezy branch.

I reinstalled 16.04 on the VPS and tried to run the wheezy version on it.

That dovecot.yml error is still there. When I grep for `item.name` I can only find it used but not defined. Where is that supposed to be defined?

**Comment by neuhaus** [comment]
Check your `vars/user.yml` file, it should define `mail_virtual_domains` there.

**Comment by neuhaus** [comment]
Please reopen if this does not fix your problem.

**Comment by dr-nate** [comment]
This issue is *likely* due to the way yaml is written in the old vs. new code. In the old code, the code was:
```
- name: Ensure mail domain directories are in place
  file: state=directory path=/decrypted/{{ item.name }} owner=vmail group=dovecot mode=770
  with_items: mail_virtual_domains
```
while in the new code it is:
```
- name: Ensure mail directories are in place
  file: state=directory path=/decrypted/{{ item.domain }}/{{ item.account }} owner=vmail group=dovecot
  with_items: '{{ mail_virtual_users }}'
```
Note the differences between the last lines. You will have to switch to the second style for all similar constructions. The easiest way to do that is to merge in these files from the current branch (checking they haven't changed too much).
