### ISSUE TITLE
Multiple configuration errors

### ISSUE THREAD

**Issue by working-name** [sovereign/sovereign#601]
Hello guys,

I'm about to give up. This has been an exercise in futility overall.

I tried both master and wheezy on 14.04, 15.04, 16.04, useless. No way in hell you can get it to work, there's just too many things that are different, packages that are discontinued, owncloud has issues with requirements not updating, there's a test repo to address that instead of actually updating the official repo, whatever. No matter how many times I tried to run ansible-playbook it kept failing in new ways, which utterly defeats the purpose of automating commands.
### changes I made while attempting to get 'wheezy' to complete on 16.04

``` py
roles/common/tasks/encfs.yml
13:# TODO: "Add mail user to fuse group" > did you forget to create the group "fuse"? Is it to be created by fuse itself? Didn't quite work if that's the case.

roles/common/tasks/google_auth.yml
7:    #TODO: "Ensure required packages are installed" > libpam-google-authenticator package is available in 16.04 now, re-enabled it
12:# TODO: "(?:Download|Extract|Install) Google authenticator" commented out. GoogleCode is dead.
41:#TODO: "Generate a timed-based, no reuse, rate-limited (3 logins per 30 seconds) with one concurrently valid code for default user" > path is not /usr/local/bin/google-authenticator for 16.04, it is /usr/bin/google-authenticator

roles/common/tasks/main.yml
72:# TODO: "Set ServerName for Apache" change 'dest=/etc/apache2/conf.d/fqdn' to  'dest=/etc/apache2/conf-available/fqdn.conf'

roles/git/tasks/cgit.yml
24:#TODO: "Build and install cgit" fails because googlecode.com is deadm and at some point it tries to pull it from there.

roles/git/tasks/gitolite.yml
34:#TODO: "Copy SSH public key to server" refers to gitolite.pub but the file is not in the git repo at all. Does one need to create it? 'ssh-keygen -t rsa -f roles/git/files/gitolite' if so.

roles/git/tasks/main.yml
5:# - include: cgit.yml tags=cgit #TODO: disabled "- include: cgit.yml tags=cgit" because it fails to compile, wants some googlecode thing.

roles/mailserver/files/etc_opendmarc_import.sql
5:-- TODO: lastsent TIMESTAMP NOT NULL DEFAULT '2016-01-01 12:00:00', => the default value was causing an error on import with postgresql 9.5+173 on xenial

roles/mailserver/tasks/dovecot.yml
33:# TODO: "Install Postgres 9.1 for Dovecot on older distributions" this needs to skip on xenial, 9.1 is not available.

roles/mailserver/tasks/dspam.yml
17:    #TODO: dspam is not available in xenial, master branch not using it anyway

roles/mailserver/tasks/main.yml
5:#TODO: disabling dspam, it is not available in xenial, and was dropped in the master branch too

roles/mailserver/tasks/postfix.yml
1:# TODO: "Install Postgres 9.1 on older distributions" needs to be skipped when on 16.04
33:#TODO: Added pkg=postgresql only, for xenial, before the password change is attempted
39:# TODO: this will fail if postgresql is not installed prior to this step "Set postgres password"

roles/mailserver/tasks/solr.yml
22:#TODO: "Copy tweaked Tomcat config file into place" update tomcat6 references to tomcat7, grab etc_tomcat7_server.xml from 'master' branch
31:#TODO: "Create Solr index directory" update tomcat6 group and owner to tomcat7

roles/mailserver/tasks/z-push.yml
1:# TODO: "Install required packages for z-push" z-push.yml remove deprecated php5 reference, leave php as default
48:#TODO: "Configure z-push apache alias and php settings" is targetting non trusty, but xenial does not apply. adding != 'xenial'

roles/monitoring/tasks/collectd.yml
16:#TODO: "Install collectd dependencies on distributions other than wheezy" librrd2 is not available in xenial. Trying librrd instead

roles/news/tasks/selfoss.yml
20:# TODO: "Install selfoss dependencies" - php5 not shipped with xenial replacing with php (which is php7.x)

roles/owncloud/tasks/owncloud.yml
5:# TODO: "Install Postgres 9.1 on distributions other than Ubuntu Trusty" postgresql is attempting to install for the third time in owncloud.yml - disabling.
19:# TODO: "Install ownCloud dependencies" requesting libapache2-mod-php5 however on xenial libapache2-mod-php should suffice (most likely php7.x). Also php-apc is now php-apcu on xenial
74:#TODO: add ownCloud repo for 16.04 apt_repository: repo='deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_16.04/ /'
75:#TODO: ownCloud test repo, which is temporary ... should no longer cry about php5 'deb http://download.owncloud.org/download/repositories/9.0:/testing/Ubuntu_16.04/ /'. Need to get key as well sudo wget -nv https://download.owncloud.org/download/repositories/9.0:/testing/Ubuntu_16.04/Release.key -O Release.key && sudo apt-key add - < Release.key
88:# TODO: "Install ownCloud (possibly from OpenSuSE repository)" => needs owncloud-server as well, but the repo contains old code so ignore. ownCloud maintainer is lazy and has yet to update dependencies to php7 from December 2015... this has to be installed manually or use a temporary repo (no good for long term) https://github.com/owncloud/core/issues/20963

roles/readlater/tasks/wallabag.yml
14:#TODO: "Install wallabag dependencies" update dependencies for xenial, no php5 there.

roles/webmail/tasks/roundcube.yml
21:# TODO: "Install Roundcube on Ubuntu 14.04 LTS" add or ansible_distribution_release == 'xenial', names of packages match
72:# TODO: "Enable php5-mcrypt" php7 is the default php package on xenial, updating path to /etc/php/7.0/mods-available/ and /etc/php/7.0/fpm/conf.d/ respectively
```

Then I figured since master is about 200 commits ahead of wheezy it shouldn't be as neglected. Still no luck there. I have a fresh Debian 8.6, I ran ansible using master branch, and at the end of it all (which by some miracle was able to complete) I've got a borked setup. Nothing accepts any of the passwords, except for znc :)
- there was no sqlite3 installed, roudcube never created its database file in /decrypted. If you inject the sqlite.initial it won't work. Trying to log in says Invalid request! No data was saved, nothing is logged about the error anywhere.
- owncloud says 403
- IMAP won't accept my password
- news says an error occured
- wallabag does not accept my password

What else can I possibly try to get this to work? Other than manually creating the setup...

**Comment by mikeashley** [comment]
Wheezy was never updated to run on distributions that use systemd.  Master does not support Ubuntu distributions yet.

If you are deploying from master on Debian 8, what errors do you see?  Perhaps you are misconfiguring your setup before running the playbook?

**Comment by working-name** [comment]
(Debian 8) No errors other than /encrypted/* not being found. The second was about not being able to start OpenVPN but that's because TUN/TAP was off for my VPS. All the rest were yellow and green statuses.   
  

  
I'll post my configuration once I get to a computer.   
  
  
  

  
>

**Comment by working-name** [comment]
Errors:
```yaml
NOTIFIED: [vpn | restart openvpn] *********************************************
failed: [domain.here] => {"failed": true}
msg: Job for openvpn@server.service failed. See 'systemctl status openvpn@server.service' and 'journalctl -xn' for details.


TASK: [common | Check if the /encrypted directory is empty] *******************
failed: [domain.here] => {"changed": false, "cmd": "ls /encrypted/*", "delta": "0:00:00.011476", "end": "2016-10-15 03:54:24.539126", "rc": 2, "start": "2016-10-15 03:54:24.527650", "stdout_lines": [], "warnings": []}
stderr: ls: cannot access /encrypted/*: No such file or directory
...ignoring
```

My [config](https://gist.github.com/working-name/4843c1985040bdb749983c615b463cea).

**Comment by working-name** [comment]
Ran the playbook on Debian 8.5 x64, this time I'm able to log in via IMAP/SMTP. However not much else is improved. 

If you'd like to see the verbose playbook log, [here it is](https://gist.github.com/working-name/7540a91f519b16d28f98de391e423d7f).

I'm going to attempt to document what I find, just in case it may be useful to you. If not, just let me know, I'll close the issue.

1. Wallabag pgsql database has the structure but no contents. Also db structure doesn't match what I find references in wallabag's issues concerning changing username (which is a big no no) and/or password.
2. OwnCloud is borked. Checked apache, there shouldn't be a problem, but it's serving `autoconfig.autoconfig.com` on `cloud.domain.com`. I'm missing something, I'm sure but at the moment it makes no sense.

**Comment by mikeashley** [comment]
Documenting will be helpful if you can get to root cause.  I have no personal experience with wallabag.  As for owncloud, it deploys properly on a test server I use, so I am interested in understanding what went wrong in your case.

**Comment by working-name** [comment]
Well I'm not sure what's different about your test server, but my OpenVZ VPS and my other VMWare Fusion Debian 8 instances behave the same. No errors while deploying, however once deployed:

1. Roundcube complains about not being able to connect to the database (might be connected to the fact that /decrypted/* is skipped while deploying, I can't find the sqlite file referenced in roundcube's config)
2. read., the wallabag installation: database has tables created but everything is blank
3. owncloud installation is serving autoconfig. (I see the mail folder with config-v1.1.xml). `/var/www/owncloud/config/config.php` is blank. And again, nothing in the vhost config suggests it should be serving `/var/www/autoconfig`. This is odd.
4. selfoss installation does not accept any logins. It's unclear whether it's trying to get to a non existing sqlite.db file in the webdir under data/sql/something.db or it's failing to pull anything from the local mysql install, which by the way does not have a database named "selfoss", and it's using the root user to access mysql which in my opinion should not have a blank password in the first place.

How do you usually debug this? Looking at the verbose log doesn't tell me much, as ironic as that sounds :)

**Comment by working-name** [comment]
Yeah, I give up. 

If any one of you developers want to try your hand at deploying on my VMWare Debian 8 and see it fail live, let me know :)

**Comment by Titan-C** [comment]
I experience the the same problems on my openVZ VPS as listed in https://github.com/sovereign/sovereign/issues/601#issuecomment-255566608

**Comment by Titan-C** [comment]
I just managed to get a development environment as stated in the wiki, with virtualbox and vagrant. I see the exact same problems as in my OpenVZ VPS.

**Comment by working-name** [comment]
Remember, @mikeashley this is not openVZ only, it's also VMWare, which is a full virtualization, it does not use the local kernel. I'll do my best to find some time to set up a physical debian box and test it out.

@Titan-C I tried to troubleshoot the playbook but it's a mess. The most you can do with it is get back the output of commands sent to the server with `-v` flag, and if you set the ENV  `ANSIBLE_KEEP_REMOTE_FILES=1`, `~deploy/.ansible/tmp/*` will not be removed. However, as far as I'm concerned those two are as useless as can be. Nothing in the command output shows me an error, and the temp files are a mess of auto-generated python scripts. So I gave up because it would take an insane amount of time to try to untangle that. Meaning you're better off manually installing each piece of software that failed to properly deploy. sovereign is a good starting point, it saves you some time, but that's where it stops.

**Comment by mikeashley** [comment]
I reproduced a number of your problems with the Vagrant-based VM.

* PR #609 addresses the problem you were having with Roundcube.
* Regarding owncloud and newebe, check /var/log/apache2.  I find that apache is seeing requests to autoconfig.sovereign.local in those cases.  I don't know why it is correct for news and mail.  I think we're seeing an interaction between host lookup and Apache that doesn't happen in a properly-configured server.  (My test server is a full Linode instance with its own domain.)
* Beware, selfoss and newebe may still have configuration problems.  If you find any, a PR to correct them would be most welcome.  Personally I don't use either of these.

**Comment by Titan-C** [comment]
> I think we're seeing an interaction between host lookup and Apache that doesn't happen in a properly-configured server. (My test server is a full Linode instance with its own domain.)

What is a properly-configured server? Isn't it this project about configuring the server? I'm also testing online on a VPS with its own domain and I also see owncloud being served to autoconfig.

**Comment by mikeashley** [comment]
This thread seems to have run its course with no reproducible bugs.
