### ISSUE TITLE
no service or tool found for: openvpn@server

### ISSUE THREAD

**Issue by hippich** [sovereign/sovereign#603]
I am in the middle of upgrade from wheezy to jessie and most of it seems to work except vpn role. Getting error about not being able to find service 'openvpn@server' despite `systemctl enable openvpn@server` in command line appears to work just fine. Any clues on how to debug that?

```
fatal: [sovereign.host.com]: FAILED! => {"changed": false, "failed": true, "msg": "no service or tool found for: openvpn@server"}
```

**Comment by lukecyca** [comment]
I recently did the upgrade and had no issues with OpenVPN.

What task was this in?

**Comment by hippich** [comment]
```
TASK [vpn : Enable OpenVPN server systemd service unit] ************************
```

**Comment by hippich** [comment]
So I restarted server after upgrade from wheezy to jessie and it appears like it solved this problem, therefore i am closing this issue.
