### ISSUE TITLE
Task list for postfix is a bit brittle

### ISSUE THREAD

**Issue by hippich** [sovereign/sovereign#607]
So I was debugging this issue for awhile (i am total newb to ansible) - no matter what i do - i would never get new email account created in the Postgres. It turned out that importing sql happens as a result of "Copy import.sql" task, which in turn notifies import task. Problem is - if you stop deployment in the middle of the process but after import.sql is copied and before import task is run, next re-run of deployment will completely ignore importing, since nothing did change during copy task...

So I was wondering if that something ansible playbook should take care of (may be run import sql always, not only when import.sql file changes) or may be there is a flag somewhere to trigger notify to always run? 

I personally resolved it by SSHing into server and manually deleting /etc/postfix/import.sql

**Comment by mikeashley** [comment]
I am not sure why the import script is run in a handler.  Perhaps other maintainers have insight?  It looks to me that schema changes could be handled in a way similar to the way timezone reconfiguration happens in the common role.  This would shorten the window in which termination of a deployment run leaves the server in a bad state.  A PR would be welcome if you are interested.

**Comment by hippich** [comment]
The easiest fix would be to add `changed_when: true` to the Copy import.sql` task, this should force re-import sql files always (I do not see immediate problems with it)

But that does not makes deployment window you mentioned smaller. Also, could you point me to timezone handling part?
