### ISSUE TITLE
How do I train rspamd?

### ISSUE THREAD

**Issue by hippich** [sovereign/sovereign#611]
From my understanding sovereign moved away from dspam to rspamd. I manually removed plugin configuration from dovecot and apt-get remove dspamd itsef (had it there since debian wheezy) - Otherwise I would get errors moving messages to the Junk folder.

Now files move to spam folder just fine but I see nothing there to actually tell rspamd to look into junk folders to learn about spam.. Any pointers to how I can see if it operates normally?

**Comment by SavageCore** [comment]
Use the dovecot antispam plugin to pass SPAM and HAM over to rspamc

https://kaworu.ch/blog/2014/03/25/dovecot-antispam-with-rspamd/

**Comment by hippich** [comment]
So i checked - it appears that dovecot_antispam plugin is installed after sovereign is run, but plugin configuration is not. Is this is simply missed part or it was omitted on purpose?

**Comment by SavageCore** [comment]
I'm not sure, I haven't actually deployed with sovereign yet. Config is easy enough and someone should make a PR!

**Comment by lukecyca** [comment]
Fixed with #617. Note that detected spam still won't be automatically moved or deleted. That requires #626.
