### ISSUE TITLE
Invalid letsencrypt certificates created for news, read, autoconfig and cloud.

### ISSUE THREAD

**Issue by tushartyagi** [sovereign/sovereign#622]
I have followed the installation guide as [here](https://github.com/sovereign/sovereign/wiki/Setting-up-on-DigitalOcean-with-Debian-7-(INCOMPLETE)) and official readme.md.

The installation went without any errors and I am able to access the `TLD` and `www`, `mail` subdomains. But if try to access `news`, `read`, `autoconfig`, and `cloud` subdomains, I am getting an invalid certificate error that the certificate is issued for TLD and is not for these 3 subdomain(s) -- although I am able to move forward to the actual apps.

Is Let's Encrypt only configured for the `www` and `mail` subdomains? Is there anything that I am missing?

**Comment by lukecyca** [comment]
Only a single certificate is generated, and it will have a CN of your main domainname (example.com). It will have SANs (Subject Alternative Name) for all the subdomains for each service (news.example.com, etc.).

See "Can I get a certificate for multiple domain names (SAN certificates)?" in the [Let's Encrypt FAQ](https://community.letsencrypt.org/t/frequently-asked-questions-faq/26).

Investigate your certificate details in a browser and make sure all of the SAN entries are there and are correct. These are generated within `roles/common/files/letsencrypt-gencert`.
