### ISSUE TITLE
Prosody variables (as defined in group_vars/soverign) don't seem to be in scope when executing prosody tasks

### ISSUE THREAD

**Issue by cacciatc** [sovereign/sovereign#624]
On Debian 8.6 x64 DigitalOcean droplet.

I get the following error when attempting to setup prosody (sames happens to item.name, but I hard-coded it for testing):

```
TASK [xmpp : Create Prosody accounts] ******************************************
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'unicode object' has no attribute 'password'\n\nThe error appears to have been in '/home/deploy/sovereign/roles/xmpp/tasks/prosody.yml': line 29, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create Prosody accounts\n  ^ here\n"}
        to retry, use: --limit @/home/deploy/sovereign/site.retry

PLAY RECAP *********************************************************************
xxx.xxx.xxx.xxx              : ok=141  changed=10   unreachable=0    failed=1
```

Tried commenting out the prosody_accounts in roles/xmpp/defaults/main.yml.

Contents of relevant portion of group_vars/soverign:
```
# xmpp
prosody_admin: "{{ admin_email }}"
prosody_virtual_domain: "{{ domain }}"
prosody_accounts:
  - name: "{{ main_user_name }}"
    password: throwaway
```
I believe the prosody_admin and prosody_virtual_domain are defined when the prosody tasks are ran (or at least there were no errors there). So I don't think I am messing up the host scope.

**Comment by sigmafeud** [comment]
I think this is a bug in sovereign/roles/xmpp/tasks/prosody.yml, line 31.
`with_items: prosody_accounts`
should be 
`with_items: "{{ prosody_accounts }}"`
but I'm totally new to ansible/yaml so don't take my word for it.

**Comment by cromulus** [comment]
@sigmafeud: Nope. still fails.
