### ISSUE TITLE
Is this run locally or remotely on the VPS?

### ISSUE THREAD

**Issue by OKNoah** [sovereign/sovereign#632]
I'm stuff with a "Could not resolve hostname" problem. And I'm wondering why do I need to resolve a hostname if I'm just installing this on the remote server itself? Then from reading another comment, I think maybe I'm supposed to do all this on my local machine?

**Comment by lukecyca** [comment]
Ansible is run on your local machine, and configures a remote machine. This allows you to target a brand new server with no dependencies beyond a default distro install.

It is also possible to run it "from within" the target server, and have it target localhost. However that is non-standard, somewhat advanced usage.

Please re-open if this doesn't make sense and you'd like further clarification. Cheers!

**Comment by OKNoah** [comment]
https://github.com/sovereign/sovereign/pull/634
