### ISSUE TITLE
Is giving the deploy user password-less sudo really optional?

### ISSUE THREAD

**Issue by OKNoah** [sovereign/sovereign#633]
When I try deploy _without_ the optional password-less deploy user, it fails, saying a password was needed.

**Comment by OKNoah** [comment]
https://github.com/sovereign/sovereign/pull/634

**Comment by ariddell** [comment]
This at least does seem like a bug. Was the user in question in the ``sudo`` group?

**Comment by neuhaus** [comment]
fixed by #634
