### ISSUE TITLE
Cannot determine credentials for some services

### ISSUE THREAD

**Issue by swriddle** [sovereign/sovereign#636]
Hi,
I just finished setting up sovereign on Debian Jessie. Unfortunately, I am unable to log into RoundCube or wallabag, as I do not know what username or password was set. Using the value under secret/selfoss_password_hash, I am able to log into selfoss, but I get an immediate error. Is that the intended password?

**Comment by mikeashley** [comment]
You log into Roundcube using your email credentials, which are configured in `group_vars` per instructions in `README.md`.
