### ISSUE TITLE
Use rspamd/rmilter for greylisting; remove Postgrey

### ISSUE THREAD

**Issue by lukecyca** [sovereign/sovereign#637]
[Rspamd's greylisting module](https://rspamd.com/doc/modules/greylisting.html) is enabled by default in our configuration, so it is already performing greylisting. We previously used (and still use) Postgrey as well. I think this means we are currently greylisting _twice_.

We need to verify that Rspamd's greylisting is working as intended, and then remove Postgrey completely.

**Comment by Dosenpfand** [comment]
I don't think that the rspamd greylisting module is active by default on Debian 8 (and therefore at the moment when using sovereign).
What i did to check:

- Disable postgrey by removing
`check_policy_service inet:127.0.0.1:10023,` from `roles/mailserver/templates/etc_postfix_main.cf.j2 => All mails arrived instantly, so apparantly no greylisting active
- Search for the textstring `greylist` `in /etc/rspamd/*` => No appropriate results.

**Comment by lukecyca** [comment]
@Dosenpfand thanks for investigating. I would really like to see us move away from postgrey and then ensure that rspamd's greylisting is enabled and working.

If you want to do more work towards this or take a stab at a PR, I'll happily help test it on my own installation and help get it merged.

**Comment by Dosenpfand** [comment]
@lukecyca Unfortunately I will not have time to work in this in the foreseeable future. Additionally I kept disabled postgrey the last month and did not see any spam hitting my inbox.

**Comment by mikeashley** [comment]
With rspamd 1.6 the greylisting module is active by default.  See `/etc/rspamd/modules.d/greylist.conf`.  I am turning off postgrey and will report back what I find in a couple of weeks.

**Comment by mikeashley** [comment]
Fixed with PR #716.
