### ISSUE TITLE
Digital Ocean configured with apache mpm_event

### ISSUE THREAD

**Issue by adborden** [sovereign/sovereign#638]
When the common role restarts apache, the service fails to restart because apache is configured for threading with `mpm_event` but php is not.

```
[Tue Dec 27 16:18:49.710876 2016] [:crit] [pid 5799:tid 139995165316992] Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe.  You need to recompile PHP.
```

I'm running Debian 8 on Digital Ocean. I don't see any configuration for proxy_fcgi or php-fpm in the playbook, so I assume this is just a difference in the Digital Ocean defaults? I replaced `mpm_event` with `mpm_prefork` and apache restarts.

```
a2dismod mpm_event
a2enmod mpm_prefork
```

**Comment by adborden** [comment]
Howdy, just curious why this was closed.

**Comment by mikeashley** [comment]
I closed it, because it seemed to be an issue specific to Digital Ocean, and there have been no comments on it.  What would you propose the next step to be?  I'm all for keeping this open if there is going to be movement on the issue.

**Comment by adborden** [comment]
Yeah, it looks like it is an issue specific to DO if no one else has run into it. I suspect that sovereign doesn't want to support this kind of provider specific quirk. But maybe this is something that could be captured in the documentation somewhere like the wiki? What has sovereign done for similar issues?

**Comment by mikeashley** [comment]
We use the wiki for issues like this.

**Comment by neuhaus** [comment]
If you have a pull request that makes sure that `mpm_prefork` is used without breaking things, we could merge that.
