### ISSUE TITLE
Syntax Error while loading YAML

### ISSUE THREAD

**Issue by chuanhhoang** [sovereign/sovereign#639]
While trying to run ansible-play book I got this error:
```
sudo ansible-playbook -i --ask-sudo-pass ./hosts site.yml
Password:
Sorry, try again.
Password:
 [WARNING]: Host file not found: --ask-sudo-pass

 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! Syntax Error while loading YAML.


The error appears to have been in '/Users/doanchu/Github/test/sovereign/hosts': line 4, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# put your host's IP address or domain name below
host.example.net
^ here
```

**Comment by TylerNakamura** [comment]
did you carefully read step 4 and replace that line?

**Comment by chuanhhoang** [comment]
In fact, yes. The problem is at this line: 

6. Run the Ansible Playbooks
ansible-playbook -i --ask-sudo-pass ./hosts site.yml

The format is incorrect. Please update the README

**Comment by Peyphour** [comment]
Solution to this problem : 
> Run the Ansible Playbooks `ansible-playbook -i --ask-sudo-pass ./hosts site.yml`
Should be replaced with `ansible-playbook -i  ./hosts --ask-sudo-pass site.yml`

**Comment by morenoh149** [comment]
@Peyphour please submit a PR

**Comment by ariddell** [comment]
Fixed.
