### ISSUE TITLE
php5 no longer supported on Digital Ocean Ubuntu (low priority)

### ISSUE THREAD

**Issue by alexec** [sovereign/sovereign#642]
This is minor one for me (as I do not plan to use the components that require it), but my server does not have php5 available anymore.

**Comment by neuhaus** [comment]
What OS (and version) do you use?

**Comment by alexec** [comment]
Ubuntu on Digital Ocean. Very recent version.

**Comment by neuhaus** [comment]
Ubuntu 16.10 is not supported by Sovereign. We only support the LTS versions of Ubuntu (14.04 and 16.04 currently).
We will deal with this when we switch to Ubuntu 18.04 LTS or Debian 9.

However, if you can install the php7 packages offered by Ubuntu 16.10 (and Ubuntu 16.04) and tell us what breaks, we can start working on that. Please open a new bug for that. 

Thanks!
