### ISSUE TITLE
issues with initial run of ansible-playbook for install

### ISSUE THREAD

**Issue by snapek** [sovereign/sovereign#645]
When I run the ansible-playbook -i ./hosts site.yml I get a conneciton error.  I have generated the password hash both ways listed on the install instructions, and get a different hash result every time I run either command (is that normal?)

Either way, this is the result and I'm unable to proceed with the install.

[15:40][snapek@host][~/sovereign]$ ansible-playbook -i ./hosts site.yml

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
fatal: [sov.host.here]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
 [WARNING]: Could not create retry file 'site.retry'.         [Errno 2] No such file or directory: ''

PLAY RECAP *********************************************************************
sov.host.here            : ok=0    changed=0    unreachable=1    failed=0

**Comment by Titan-C** [comment]
you are trying to ssh into the wrong domain: `sov.host.here`. You have
to put in you `hosts` file the domain or the IP of your server machine.

> I have generated the password hash both ways listed on the install
> instructions, and get a different hash result every time I run either
> command (is that normal?)

yes

**Comment by snapek** [comment]
Yeah, I tried both the hostname, the fqdn and the ip of the target machine all with the same results.  I just edited the example above to read sov.host.here for privacy purposes.

**Comment by der-gee** [comment]
I had similar problems, but it was my fault: In ran the playbook from the VPS where sovereign is running now. So i had to switch to the deploy user, create a ssh-key for the delpoy user and put the public key in the authorized_keys file before running the playbook. Just to be sure i didn't omit the `--ask-sudo-pass` argument. Just in case you're running the same setup :-)
