### ISSUE TITLE
CGit isn't configured correctly.

### ISSUE THREAD

**Issue by KnightHawk3** [sovereign/sovereign#666]
I encountered this bug on a fresh debian 8.0 image on linode.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784608;msg=5

The steps in the bug report fixed it for me.

Also my output is still blank and the default highlighter can't find pygments, I haven't researched it enough to work out why, will update when I work it out

**Comment by Titan-C** [comment]
PR #668 installs the python 3 dependencies of cgit to use pygments, give it a try.

**Comment by mikeashley** [comment]
I am closing this since there are no further comments, and the fix has been merged.
