### ISSUE TITLE
opendmarc sends reports with personal email

### ISSUE THREAD

**Issue by adborden** [sovereign/sovereign#676]
I get bounces every once in a while from DMARC reports. That's normal, but it's a little concerning because they are to my personal email rather than an admin email like `postmaster@domain.name`. This is because we're setting `--report-email` as the user's address when it should probably postmaster@.

I would consider this an information leak because a spammer could send spam to any address on your domain and the DMARC report would include your real email address in the report back to the spammer's mail server.

**Comment by neuhaus** [comment]
I like the idea however we are not creating the postmaster alias in the virtual mailbox table by default so "postmaster" will not necessarily be a working email address (yes, that's a bug).

**Comment by neuhaus** [comment]
Thanks for the patch!
