### ISSUE TITLE
Outgoing mail from virtual mailbox not being DKIM signed

### ISSUE THREAD

**Issue by bmiller59** [sovereign/sovereign#686]
I have tested my email settings for a secondary virtual mailbox using check-auth@verifier.port25.com and it is not being DKIM signed. The first original mailbox setup by sovereign was being signed. How do I enable DKIM signing for all virtual mailboxes? Thank you. This is what  check-auth@verifier.port25.com reported for that section (changed my email address for privacy reasons).

----------------------------------------------------------
DomainKeys check details:
----------------------------------------------------------
Result:         neutral (message not signed)
ID(s) verified: header.From=test@example.com
DNS record(s):

----------------------------------------------------------
DKIM check details:
----------------------------------------------------------
Result:         neutral (message not signed)
ID(s) verified: 

NOTE: DKIM checking has been performed based on the latest DKIM specs
(RFC 4871 or draft-ietf-dkim-base-10) and verification may fail for
older versions.  If you are using Port25's PowerMTA, you need to use
version 3.2r11 or later to get a compatible version of DKIM.

**Comment by bmiller59** [comment]
I resolved the issue by following this tutorial. Worked like a charm. https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-dkim-with-postfix-on-debian-wheezy

**Comment by Titan-C** [comment]
can you make a pull request with the contents of the tutorial into a
playbook so that everyone else can benefit from it?
