### ISSUE TITLE
catch all email

### ISSUE THREAD

**Issue by cdiaz1971** [sovereign/sovereign#687]
I've see how to add new mailboxes as well as virtual aliases to point to other mailboxes.  Is there a way to create a catch-all alias so anything@domain goes to one user or anythingnotmatchingexistingalias@domain goes to a user?

Thanks,

C

**Comment by dragonmantank** [comment]
I'd be interested in this as well. From what I've gathered it should be just adding a bare alias for `@domain.com` to a virtual user, but the SQL gets screwy. 

I tried modifying the install as suggested at https://workaround.org/ispmail/wheezy/connecting-postfix-to-the-database , but then postfix started rejecting all my e-mail addresses for some reason.

**Comment by neuhaus** [comment]
You may also be interested in the `recipient_delimiter` option of dovecot.
That way you can use something like 
user-1@example.com or
user-abc@example.com or
user-microsoft@example.com

and once you start receiving spam on one particular address you know who leaked it and you can block mail sent to that address using SIEVE.

**Comment by neuhaus** [comment]
@dragonmantank if you could contribute some documentation to the Wiki here at github that'd be very helpful!

Other than that I'm closing this issue. There is nothing that's Sovereign specific with regards to catch-all.
