### ISSUE TITLE
etc_dovecot_conf.d_90-plugin.conf is orphaned

### ISSUE THREAD

**Issue by Xeboc** [sovereign/sovereign#691]
As of this commit:

https://github.com/sovereign/sovereign/commit/ecaa4c23308adbdb5d76937296090ca7a6cc5944#diff-60a2d80cf2f6bad5c7a33594b338f4aa

When dspam.yml was removed, 90-plugin.conf is orphaned and never copied over.  Is it needed for solr functionality?  I'm just diving into this project, so I haven't tested the solr functionality myself, and was hoping a maintainer knew.

https://github.com/sovereign/sovereign/blob/master/roles/mailserver/files/etc_dovecot_conf.d_90-plugin.conf

**Comment by neuhaus** [comment]
paging @al3x

**Comment by mikeashley** [comment]
Fixed with PR #716.
