### ISSUE TITLE
Ansible failed to connect

### ISSUE THREAD

**Issue by wjjessen** [sovereign/sovereign#692]
I have set up a Debian server (ssh'd in as username = "root") as instructed, setting up for passwordless sudo. I'm using DigitalOcean and have added my laptop's ssh key, so I don't have to type in a password after typing "root@123.123.123.123" in the terminal.

I am now trying to run the setup from my laptop (username is macuser, not root), but get an unreachable error. What am I doing wrong?

fatal: [123.123.123.123]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey).\r\n", "unreachable": true}
	to retry, use: --limit @/Users/macuser/Downloads/sovereign-setup/sovereign/site.retry

**Comment by wjjessen** [comment]
Fixed the problem by copying the authorized_keys file from root to the deploy user: 
`cp ~/.ssh/authorized_keys /home/deploy/.ssh/authorized_keys`

**Comment by neuhaus** [comment]
If this is missing in the documentation, a pull request would be welcome :+1:
