### ISSUE TITLE
Ansible list tags empty

### ISSUE THREAD

**Issue by iboxifoo** [sovereign/sovereign#699]
Since updating to Ansible v2.3.x, I've been unable to run specific tags in Sovereign. For example, I'd often run the postfix tag after adding an email alias. Now, ansible still runs without errors but no tags are run (i.e. it "completes" in seconds). The specific command I'd run is the same as in the README here on the project.

Wondering if anyone else is experiencing the same issue with newer version of Ansible?

**Comment by iboxifoo** [comment]
This is taken from the blog post announcing Ansible 2.0, and may point toward the issue I've experienced: https://www.ansible.com/blog/ansible-2.0-launch

> Dynamic Include Problems
> 
> Due to the fact that include tasks are now evaluated at run time, Ansible no longer knows ahead of time about any tasks contained within files which have yet to be included. This presents problems in several situations (which we intend to correct in future versions):
> 
> Tags on tasks are not seen until the include is processed, so tags should now be specified on the include task rather than on individual tasks within the include, otherwise they will not be seen. Likewise, the --list-tags option will not show tags contained only in the include files.
> 
> Handlers in includes will not be seen when a task attempts to notify them, so handlers should avoid using includes at this time.
> 
> Missing Tags
> 
> Ansible 2.0 does not currently raise an error if a non-existent tag is specified via --tags or --skip-tags.  This is also related to the dynamic include problem above, and we intend to address this once the above include problems are resolved.

**Comment by neuhaus** [comment]
Sounds as if future versions of Ansible will fix this issue?

**Comment by iboxifoo** [comment]
I'm going to close this issue as everything continues to work fine on Ansible 1.9.
