### ISSUE TITLE
SHA2017 sovereign workshop

### ISSUE THREAD

**Issue by neuhaus** [sovereign/sovereign#700]
I will be doing a [workshop](https://program.sha2017.org/events/131.html) on Sovereign at [SHA2017](https://sha2017.org) on August 7th 2017.

The workshop's focus will be on using Sovereign on your own low-power hardware in your own home, combining it with a VPS at an ISP to use its IP address for the services running on the Sovereign box, circumventing issues with dialup IPs.

I will also try to recruit new project contributors. :crossed_fingers: 

Is there anyone else who will be at the camp? It may be a good opportunity to meet in person, have a beer :beers:  and discuss future development.

**Comment by JoKeyser** [comment]
Hi @neuhaus, I'll be there and visit your workshop, looking forward to it. I'm a newcomer to the https://github.com/freedombox/ project, and think there's a lot of shared value with yours. Maybe collaborations are possible :).

**Comment by neuhaus** [comment]
Thanks for the interesting discussions!
