### ISSUE TITLE
rspamd repository unavailable on arm machines

### ISSUE THREAD

**Issue by neuhaus** [sovereign/sovereign#704]
When trying to use sovereign on a raspberry pi 3 I ran into the problem that the rspamd repository doesn't offer binaries for the "armhf" architecture.

On a Raspberry Pi 3 with Raspbian 8, I can see the following Ansible Variables that we can use to detect this platform:

        "ansible_machine": "armv7l",
        "ansible_architecture": "armv7l",

There is the stock rspamd package provided by Raspbian (jessie) but it's still version 0.6.10.

@carljm  Whats the minimum version of rspamd required by our setup?

**Comment by carljm** [comment]
@neuhaus I don't have any idea, sorry :/
