### ISSUE TITLE
project member

### ISSUE THREAD

**Issue by neuhaus** [sovereign/sovereign#706]
Hi @al3x @ariddell @jplock @lukecyca @mikeashley 

I suggest we try to get @synchrone on board as a sovereign project member. He's contributed some valuable patches to the project recently. Any objections?

**Comment by mikeashley** [comment]
No objections from me.  I really like the password hashing improvements.

**Comment by ariddell** [comment]
No objections.

**Comment by neuhaus** [comment]
I talked to synchrone and he had some good ideas and wants to support the project in the future.
@al3x or @lukecyca please add him to the committers.

**Comment by jplock** [comment]
sounds good to me

**Comment by lukecyca** [comment]
Sounds like we have rough consensus here. I've added @synchrone as a project member with commit access.
