### ISSUE TITLE
Playbook fails connecting. SSH works. 

### ISSUE THREAD

**Issue by TinkerFu** [sovereign/sovereign#710]
Debian 8. Clean vps install. 
DNS is working including rdns. 
SSH works fine from command line. 

using:  ansible-playbook -vvv -i ./hosts --ask-sudo-pass site.yml

I get:

```
fatal: [mail.domain.com]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n", 
    "unreachable": true
}
```

**Comment by TinkerFu** [comment]
I had to use -k then it was happy.

**Comment by neuhaus** [comment]
Which version of ansible are you using?
