### ISSUE TITLE
Failed to connect to the host via ssh, VMWare

### ISSUE THREAD

**Issue by ECWeb** [sovereign/sovereign#712]
im trying to install this on ubuntu 14.04 inside vmware.. followed everything... 
executing this command:
sudo ansible-playbook -i ./hosts --ask-sudo-pass site.yml

but it say..
fatal: [mail.server.hosttest.com]: UNREACHABLE => {
"changed": false,
"msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n",
"unreachable": true
}

**Comment by ECWeb** [comment]
I think it should be added in the documentation..
========
hosts
========
[sovereign]
ip.add.host.name ansible_ssh_user=<user> ansible_ssh_pass=<pass>

**Comment by neuhaus** [comment]
There is a step in the README:

    nano /home/deploy/.ssh/authorized_keys

This means at this point you should edit the authorized_keys file and put your ssh public key(s) there. Did you do that?
