### ISSUE TITLE
Installation fails due to missing owncloud folder

### ISSUE THREAD

**Issue by der-gee** [sovereign/sovereign#715]
Hello everyone,

i'm trying to get a new installation running. Everything works like a charm, expect the owncloud installation:

```
TASK: [owncloud | Move ownCloud data to encrypted filesystem] ***************** 
failed: [my-host.tld] => {"changed": true, "cmd": ["mv", "/var/www/owncloud/data", "/decrypted/owncloud-data"], "delta": "0:00:00.014927", "end": "2017-11-05 04:03:43.970496", "rc": 1, "start": "2017-11-05 04:03:43.955569", "warnings": []}
stderr: mv: cannot stat ‘/var/www/owncloud/data’: No such file or directory
FATAL: all hosts have already failed -- aborting
```

If I create said folder by myself and start the playbook again, the installation completes, but I'll get an kind of folder like view from apache visiting the site https://cloud.my-host.tld without any content.

When the installation is done, the folder:
`/var/www/owncloud/data` contains a link to `/decrypted/owncloud-data`, which is empty 

`dpkg` lists owncloud as installed.

Can anybody provide some suggestions what could be wrong?

Thanks in advance,
der-gee

**Comment by der-gee** [comment]
I messed up and have to wait a week until further certificates can be issued :)

I think I have to change the package from owncloud to owncloud-files in the owncloud.yml.

I'll close this issue (and reopen it, if I was wrong).

**Comment by der-gee** [comment]
Hello again,

sorry, but I'm to tired to figure out how to create a pull-request.

But I've managed to complete a installation in one run with changeing owncloud to owncloud-file.

Here's the link which led me to this conclusion: [owncloud manual](https://doc.owncloud.org/server/9.0/admin_manual/installation/linux_installation.html)

```/master/roles/owncloud/tasks/owncloud.yml 
- name: Install ownCloud
  apt: pkg=owncloud-files update_cache=yes```

Worked for me.

**Comment by der-gee** [comment]
If this was a finding, it should be solved with PR #718

**Comment by neuhaus** [comment]
Let's leave the issue open until the PR has been merged.
What Linux distribution (and version) are you using?

**Comment by der-gee** [comment]
Distributor ID: Debian
Description:    Debian GNU/Linux 8.9 (jessie)
Release:        8.9
Codename:       jessie

Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19)

**Comment by mikeashley** [comment]
PR #718 was merged.
