### ISSUE TITLE
Should DMARC configuration use p=reject?

### ISSUE THREAD

**Issue by adborden** [sovereign/sovereign#719]
I don't know much about DMARC, but from what I'm hearing, I think it's considered good practice to use the "reject" policy for DMARC. This wouldn't provide any additional protection for sovereign users, but it would signal to receivers that if a message fails authentication, they should reject it and report it back to the sending domain. I believe that even having `p=none` (as suggested in the README) will still cause receivers to send reports. So I believe changing the policy to reject won't have any affect on sovereign users, it would just make it harder for folks to send spam under the guise of your domain. Of course, it makes it extra important that you have your DKIM/SPF settings correct to prevent legitimate mail from being rejected.

https://www.ftc.gov/news-events/press-releases/2017/03/online-businesses-could-do-more-protect-their-reputations-prevent
https://www.ftc.gov/system/files/documents/reports/businesses-can-help-stop-phishing-protect-their-brands-using-email-authentication-ftc-staff/email_authentication_staff_perspective.pdf

**Comment by mikeashley** [comment]
I think initially configuring `p=none` is correct, but `rua` [should be set](https://dmarc.org/overview/) also.

**Comment by mikeashley** [comment]
This discussion seems to have gone idle.
