### ISSUE TITLE
Fell at the first hurdle - 'MODULE FAILURE' would appreciate guiding in the right direction please :)

### ISSUE THREAD

**Issue by mannp** [sovereign/sovereign#721]
> ansible 2.4.1.0
>   config file = None
>   configured module search path = [u'/Users/local/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
>   ansible python module location = /usr/local/Cellar/ansible/2.4.1.0/libexec/lib/python2.7/site-packages/ansible
>   executable location = /usr/local/bin/ansible
>   python version = 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]

Having had streisand up and running well for 8 months I thought I'd be OK at this, but have failed at the first hurdle.

So I spun up a amazon ubuntu server and setup keys for the deploy user and login passwordless with the key with ssh deploy@IP ADDRESS

Executing sudo apt-get update doesn't ask for a password and executes as expected.

I have configured the host file and groups_vars/sovereign and deleted the line in the playbook referring to tarsnap as I will use borg instead.

When i run; **ansible-playbook -i ./hosts site.yml** I get;

> [DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic
> inclusions. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
> [DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about
>  this rationale.. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in
> ansible.cfg.

TASK [Gathering Facts] ************************************************************************************************************
fatal: [IP ADDRESS]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to IP ADDRESS closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/Users/local/Builds/sovereign/site.retry

PLAY RECAP ************************************************************************************************************************
<IP ADDRESS>                 : ok=0    changed=0    unreachable=0    failed=1

**Comment by neuhaus** [comment]
You need to have python installed on the target host.

**Comment by mannp** [comment]
I did wonder that, but didn't see it as part of the setup requirements or prerequisites so assumed it didn't need it.

**Comment by neuhaus** [comment]
i will add it to the README.
