### ISSUE TITLE
Fail to get certs via Let's Encrypt but DNS points to the correct places.

### ISSUE THREAD

**Issue by mannp** [sovereign/sovereign#722]
Amazon EC2 Server with Ubuntu.

TASK [common : Get an SSL certificate for DOMAIN from Let's Encrypt] **************************************************************************************

I am getting lets encrypt failures when I have a A record pointing to the correct IP Address and CNAME records for all the other items required by sovereign.

Checked them on www.whatsmydns.net and they appear ok.

I have copied the dns setup from another working server with LE, on namecheap, so its odd.

Not sure what I am missing ....?

The log states the apache service failed to start, which I presume is related to the lack of a ssl cert.

> 2017-11-29 17:14:06,921:INFO:certbot.auth_handler:Cleaning up challenges
> 2017-11-29 17:14:06,923:DEBUG:certbot.plugins.standalone:Stopping server at :::443...
> 2017-11-29 17:14:07,207:DEBUG:certbot.log:Exiting abnormally:
> Traceback (most recent call last):
>   File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 11, in <module>
>     sys.exit(main())
>   File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 861, in main
>     return config.func(config, plugins)
>   File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 786, in certonly
>     lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
>   File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 85, in _get_and_save_cert
>     lineage = le_client.obtain_and_enroll_certificate(domains, certname)
>   File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/client.py", line 357, in obtain_and_enroll_certificate
>     certr, chain, key, _ = self.obtain_certificate(domains)
>   File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/client.py", line 318, in obtain_certificate
>     self.config.allow_subset_of_names)
>   File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 81, in get_authorizations
>     self._respond(resp, best_effort)
>   File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 138, in _respond
>     self._poll_challenges(chall_update, best_effort)
>   File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 202, in _poll_challenges
>     raise errors.FailedChallenges(all_failed_achalls)
> FailedChallenges: Failed authorization procedure. autoconfig.mannuk.org (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify

fatal: [domain.com]: FAILED! => {"changed": true, "failed": true, "msg": "non-zero return code", "rc": 1, "stderr": "Shared connection to IP ADDRESS closed.\r\n", "stdout": "Saving debug log to /var/log/letsencrypt/letsencrypt.log\r\nPlugins selected: Authenticator standalone, Installer None\r\nObtaining a new certificate\r\nPerforming the following challenges:\r\ntls-sni-01 challenge for domain.com\r\ntls-sni-01 challenge for www.domain.com\r\ntls-sni-01 challenge for mail.domain.com\r\ntls-sni-01 challenge for autoconfig.domain.com\r\ntls-sni-01 challenge for read.domain.com\r\ntls-sni-01 challenge for news.domain.com\r\ntls-sni-01 challenge for cloud.domain.com\r\ntls-sni-01 challenge for git.domain.com\r\nWaiting for verification...\r\nCleaning up challenges\r\nFailed authorization procedure. read.domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout, autoconfig.domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout, news.domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout, domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout, git.domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout, www.domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout, cloud.domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout, mail.domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout\r\n\u001b[1m\r\nIMPORTANT NOTES:\r\n\u001b[0m - The following errors were reported by the server:\r\n\r\n   Domain: read.domain.com\r\n   Type:   connection\r\n   Detail: Timeout\r\n\r\n   Domain: autoconfig.domain.com\r\n   Type:   connection\r\n   Detail: Timeout\r\n\r\n   Domain: news.domain.com\r\n   Type:   connection\r\n   Detail: Timeout\r\n\r\n   Domain: domain.com\r\n   Type:   connection\r\n   Detail: Timeout\r\n\r\n   Domain: git.domain.com\r\n   Type:   connection\r\n   Detail: Timeout\r\n\r\n   Domain: www.domain.com\r\n   Type:   connection\r\n   Detail: Timeout\r\n\r\n   Domain: cloud.domain.com\r\n   Type:   connection\r\n   Detail: Timeout\r\n\r\n   Domain: mail.domain.com\r\n   Type:   connection\r\n   Detail: Timeout\r\n\r\n   To fix these errors, please make sure that your domain name was\r\n   entered correctly and the DNS A/AAAA record(s) for that domain\r\n   contain(s) the right IP address. Additionally, please check that\r\n   your computer has a publicly routable IP address and that no\r\n   firewalls are preventing the server from communicating with the\r\n   client. If you're using the webroot plugin, you should also verify\r\n   that you are serving files from the webroot path you provided.\r\nJob for apache2.service failed because the control process exited with error code. See \"systemctl status apache2.service\" and \"journalctl -xe\" for details.\r\n", "stdout_lines": ["Saving debug log to /var/log/letsencrypt/letsencrypt.log", "Plugins selected: Authenticator standalone, Installer None", "Obtaining a new certificate", "Performing the following challenges:", "tls-sni-01 challenge for domain.com", "tls-sni-01 challenge for www.domain.com", "tls-sni-01 challenge for mail.domain.com", "tls-sni-01 challenge for autoconfig.domain.com", "tls-sni-01 challenge for read.domain.com", "tls-sni-01 challenge for news.domain.com", "tls-sni-01 challenge for cloud.domain.com", "tls-sni-01 challenge for git.domain.com", "Waiting for verification...", "Cleaning up challenges", "Failed authorization procedure. read.domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout, autoconfig.domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout, news.domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout, domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout, git.domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout, www.domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout, cloud.domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout, mail.domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout", "\u001b[1m", "IMPORTANT NOTES:", "\u001b[0m - The following errors were reported by the server:", "", "   Domain: read.domain.com", "   Type:   connection", "   Detail: Timeout", "", "   Domain: autoconfig.domain.com", "   Type:   connection", "   Detail: Timeout", "", "   Domain: news.domain.com", "   Type:   connection", "   Detail: Timeout", "", "   Domain: domain.com", "   Type:   connection", "   Detail: Timeout", "", "   Domain: git.domain.com", "   Type:   connection", "   Detail: Timeout", "", "   Domain: www.domain.com", "   Type:   connection", "   Detail: Timeout", "", "   Domain: cloud.domain.com", "   Type:   connection", "   Detail: Timeout", "", "   Domain: mail.domain.com", "   Type:   connection", "   Detail: Timeout", "", "   To fix these errors, please make sure that your domain name was", "   entered correctly and the DNS A/AAAA record(s) for that domain", "   contain(s) the right IP address. Additionally, please check that", "   your computer has a publicly routable IP address and that no", "   firewalls are preventing the server from communicating with the", "   client. If you're using the webroot plugin, you should also verify", "   that you are serving files from the webroot path you provided.", "Job for apache2.service failed because the control process exited with error code. See \"systemctl status apache2.service\" and \"journalctl -xe\" for details."]}

**Comment by mannp** [comment]
Seems ports 80 and 443 have to be open on the VPS as a prerequisite :(

**Comment by pallavikarpaklu** [comment]
I am facing same issue. ansible playbook fails for command:  ansible-playbook -i ./hosts site.yml .
Ports seems to be fine for me but why does Get SSL Cert fail??!!!!

I  get the same error "Get an SSL certificate for <domanin> from Let's Encrypt"

On my linode server below are the ports currently open. 
root@localhost:~# sudo iptables -L -nv
Chain INPUT (policy ACCEPT 192 packets, 13578 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp spt:80
  110  632K ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp spt:443
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp spt:80
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp spt:80


Can someone help me to resolve this issue?
