### ISSUE TITLE
fail2ban won't start - ERROR  Found no accessible config files for 'fail2ban' under /etc/fail2ban

### ISSUE THREAD

**Issue by mannp** [sovereign/sovereign#724]
Have cut down the install to reduce the amount of issues and this one is causing me some confusion;

root@ip-172-31-80-129:/etc/fail2ban/filter.d# nano dovecot-pop3imap.conf
root@ip-172-31-80-129:/etc/fail2ban/filter.d# /usr/bin/fail2ban-client -x start
ERROR  Found no accessible config files for 'fail2ban' under /etc/fail2ban
ERROR  No section: 'Definition'
ERROR  No section: 'Definition'
ERROR  No section: 'Definition'
ERROR  No section: 'Definition'
ERROR  No section: 'Definition'
ERROR  No section: 'Definition'
ERROR  No section: 'Definition'
ERROR  Found no accessible config files for 'filter.d/sshd' under /etc/fail2ban
ERROR  No section: 'Definition'
ERROR  No section: 'Definition'
ERROR  Unable to read the filter
ERROR  Errors in jail 'ssh'. Skipping...
WARNING 'filter' not defined in 'pam-generic'. Using default one: ''
WARNING No filter set for jail pam-generic
WARNING 'backend' not defined in 'pam-generic'. Using default one: 'auto'
WARNING 'filter' not defined in 'pam-generic'. Using default one: ''
ERROR  Failed during configuration: Bad value substitution: option 'action' in section 'pam-generic' contains an interpolation key 'action_' which is not a valid option name. Raw value: '%(action_)s'

**Comment by mannp** [comment]
More definition required in supplied jail.local to allow latest ubuntu on AWS to work.

**Comment by neuhaus** [comment]
Could you elaborate?
