### ISSUE TITLE
ufw fails to enable cleanly

### ISSUE THREAD

**Issue by lukecyca** [sovereign/sovereign#73]
Following @ariddell's contribution, I switched my server to use `ufw` instead of `ferm`, and ran into this problem:

```
TASK: [Check status of ufw] ***************************************************
ok: [vps1.lukecyca.com]

TASK: [Enable ufw] ************************************************************
failed: [vps1.lukecyca.com] => {"changed": true, "cmd": ["ufw", "--force", "enable"],
"delta": "0:00:00.720280", "end": "2013-10-27 21:17:00.421354", "item": "", "rc": 1,
"start": "2013-10-27 21:16:59.701074"}
stderr: ERROR: problem running ufw-init
```

I logged in and ran it manually, and got a different error:

```
root@vps1:~# ufw --force enable
ERROR: Could not load logging rules
```

The firewall _is_ running and operating properly, but the `enable` command fails to mark itself as enabled in `/etc/ufw/ufw.conf`, so it fails to start at boot (which I think is a problem).

Upon further investigation, it seems there is a [bug](https://bugs.launchpad.net/ufw/+bug/1065297) whereby ufw logging is incompatible with our version of iptables. A fix has been committed, but it's not fixed in the version we're using (0.31.1-2). 

If we turn logging off, this bug goes away and the `enable` command works fully, but I'm not sure that's a good solution.

**Comment by davidavdav** [comment]
Thanks for figuring this out.  This problem has popped up in a Vagrant/debian-8 environment.  

But I don't understand your easy fix: "forcibly create the chain in before{,6}.rules with a lineinfile directive"---could you be more specific?
