### ISSUE TITLE
Remove njabl from check-rbl

### ISSUE THREAD

**Issue by lukecyca** [sovereign/sovereign#750]
Today I started to get this from check-rbl:
```
19.56.106.123 is listed on dnsbl.njabl.org !
19.56.106.123 is listed on combined.njabl.org !
```

It seems that this RBL has been [defunct for ages](https://en.wikipedia.org/wiki/Not_Just_Another_Bogus_List).

I have updated check-rbl to exclude it, and will update sovereign to use this new version.

**Comment by neuhaus** [comment]
Any update on this?

**Comment by neuhaus** [comment]
fixed
