### ISSUE TITLE
Debian 10.1 "buster" support (7th September 2019)

### ISSUE THREAD

**Issue by neuffer** [sovereign/sovereign#764]
Hi *
Below is an excerpt from the Debian Release Managers Announcement: 

Introduction
============

The Stable Release Managers, with the support of the rest of the
Release Team, are responsible for updates to the stable release (and
oldstable while that suite is also being supported by the Security
Team), via point releases and the stable-updates mechanism [STABLE-
PDATES].

You can see the current status of proposed updates to stable via our
BTS pseudo-package [BTS] and our tracking website. [QUEUE-VIEWER]

First 'buster' point release
============================

The first point release for Debian 10 has been scheduled for 7th
September 2019. That is slightly later after buster's initial release 
than we would normally aim for, but an earlier date has proved
difficult with DebConf and holidays.

A point release for 'stretch', Debian 9.10, will also take place on the
same day.

Following the release of 10.1, we will continue to aim for stable point
releases on an approximately two-month basis, and oldstable every three
to four months.

**Comment by neuhaus** [comment]
Hello @neuffer, i don‘t think that we need a separate issue for a Debian Point release. The Debian project tries not to break anything during the life cycle of a release, so it‘s not expected that Sovereign has to accomodate this point release in any way. Please stick to issue #757
