### ISSUE TITLE
Will it work on OpenBSD

### ISSUE THREAD

**Issue by bimonsubio1984** [sovereign/sovereign#781]
How many changes will I have to do?

Indicated as an estimate of percentage of your ansible code which will need changes.

Say 1-2% or 30-50%?

What other alternatives do I have except iRedMail on OpenBSD?
It seems at least paid iRedMail offers ansible too?

**Comment by neuhaus** [comment]
This project is quite specific in terms of dealing with packages. I think it would be a substantial effort. I'm not that familiar with OpenBSD these days. But you'll have to change a lot.
