### ISSUE TITLE
[social] FOSDEM 2020

### ISSUE THREAD

**Issue by neuhaus** [sovereign/sovereign#791]
I will be at [FOSDEM 2020](https://fosdem.org/2020/) in Brussels, Belgium this upcoming weekend. 
Please get in touch (for example by commenting here) if you'll be there and want to discuss sovereign while having a beer. 🍺

**Comment by butonic** [comment]
Hey, a lot of people from ownCloud will be at FOSDEM2020. We are sharing a booth with kopano and would love to have a beer with you, discuss sovereign, ansible, and maybe fill you in on [ocis](https://github.com/owncloud/ocis) and how we want to integrate with kopano. :beers:

**Comment by neuhaus** [comment]
Missed you @butonic when i was at your booth. See you next time!
