### ISSUE TITLE
Documentation refers to a line in hosts file but doesn't specify location

### ISSUE THREAD

**Issue by codecowboy** [sovereign/sovereign#800]
In the README, the following appears after the git config instructions (I am not using git)

`Finally, replace the host.example.net in the file hosts. If your SSH daemon listens on a non-standard port, add a colon and the port number after the IP address. In that case you also need to add your custom port to the task Set firewall rules for web traffic and SSH in the file roles/common/tasks/ufw.yml.
`

Does this mean `/etc/hosts`? If so, there is no entry for host.example.net (or my actual domain name). I also ignored this instruction as I thought it was part of the git config - its not that clear (to me, anyway).

**Comment by neuhaus** [comment]
This refers to the file hosts that comes with sovereign in the top directory.
