### ISSUE TITLE
Switch OpenVPN for Wireguard

### ISSUE THREAD

**Issue by OneCricketeer** [sovereign/sovereign#805]
WireGuard is in the Linux Kernel now, and claims to be simpler and more performant than OpenVPN

**Comment by delbonis** [comment]
WireGuard isn't nearly as production ready as OpenVPN is.  Give it another few months maybe for more mature tooling to be developed.

**Comment by cricket007** [comment]
It's less known, but it's been around for years. 

What makes something considered "production ready"?

**Comment by HumanG33k** [comment]
For me production ready is in debian stable repository. It’s mean time to add to testing and time to testing to be promote (from day 1 to publishing ~ 2 years )

**Comment by cricket007** [comment]
https://lore.kernel.org/wireguard/CAHmME9qOpDeraWo5rM31EWQW574KEduRBTL-+0A2ZyqBNDeYkg@mail.gmail.com/T/#u

**Comment by neuffer** [comment]
Ubuntu (20.04 LTS) as well as Debian (Buster) are back-porting Wireguard.

**Comment by HumanG33k** [comment]
I test it in debian stable. i have some troubles with backports but look work well with the stable kernel.

**Comment by OneCricketeer** [comment]
https://tailscale.com/blog/why-not-why-not-wireguard/

**Comment by HumanG33k** [comment]
@OneCricketeer i m pretty sure my issues were not only the debian fact but also windows in my case but since i post i face to new troubles. can t any more connect through rdp with wireguard. (and i change nothing in the configuration) But i probably miss somethings.

**Comment by OneCricketeer** [comment]
I rarely use RDP, but I would suggest using Apache Guacamole instead

**Comment by HumanG33k** [comment]
i will check that.

**Comment by neuhaus** [comment]
We're open to switching to Wireguard if someone will provide a pull request. Until then i'm closing this issue.
