### ISSUE TITLE
Allow for private git repositories

### ISSUE THREAD

**Issue by qedi-r** [sovereign/sovereign#818]
All of my git repos are private. Anything public I'd probably be forking/hosting on GitHub anyway. I would think it would be useful to add authentication to the git domain. Mirroring the email users and allowing apache to check auth via postgres would probably be the most straightforward. Driving this via an optional flag in the sovereign group_vars would probably also make sense.

Another benefit is that this would then also allow enabling gitolite as a http frontend for pushing/pulling when ssh isn't available.

**Comment by neuhaus** [comment]
If someone provides a pull request for this, it is welcome. Until then I'm closing this issue.
